project:
  type: book
  output-dir: docs

book:
  title: "H2 Data Science Practicals"
  author: "Tim Szewczyk (v1: Tom Wilding)"
  date: "2025-09-01"
  chapters:
    - index.qmd
    - P0_R_setup.qmd
    - P1_R_recap.qmd
    - P2_binomial_poisson.qmd
    - P3_normal.qmd
    - P4_t_CIs.qmd
    - P5_ANOVA_regression.qmd
    - P6_machine_learning.qmd
    - P7_appendix.qmd
  site-url: https://sz-tim.quarto.pub/h2ds-practicals
  repo-actions: [issue]
  repo-url: https://github.com/Sz-Tim/H2DS_Practicals
  favicon: figs/one_distribution.png
  downloads: [pdf, epub]
  search: true

format:
  html:
    theme: flatly
    dark: darkly
    code-fold: false
    code-block-bg: true
    code-link: true
    callout-appearance: simple
    link-external-newwindow: true
    link-external-filter: ^(?:http:|https:)\/\/\.sz-tim\.quarto\.pub/custom
    
  pdf:
    documentclass: book
    papersize: A4
    cover-image: figs/cover.png
    toc: true
    toc-depth: 2
    number-sections: true
    colorlinks: true
    prefer-html: true
    geometry:
      - top=20mm
      - right=20mm
      - bottom=20mm
      - left=20mm
      - heightrounded
    
  epub:
    cover-image: figs/cover.png
    prefer-html: true
  

callout-appearance: simple

editor: source

custom-numbered-blocks:
  classes:
    Q.: 
      boxstyle: foldbox.simple
      collapse: false
      colors: [69B7CE, 3F6F76]

filters:
- custom-numbered-blocks

execute:
  freeze: auto
