<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>H2 Data Science Practicals - 2&nbsp; Binomial and Poisson Distributions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./P3_normal.html" rel="next">
<link href="./P1_R_recap.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./P2_binomial_poisson.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Binomial and Poisson Distributions</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">H2 Data Science Practicals</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P0_R_setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R setup</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P1_R_recap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">R recap</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P2_binomial_poisson.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Binomial and Poisson Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P3_normal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Normal distribution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P4_t_CIs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">T distribution and confidence intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P5_ANOVA_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">ANOVA and regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P6_machine_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Machine Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P7_appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Appendix</span></span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#the-binomial-distribution" id="toc-the-binomial-distribution" class="nav-link active" data-scroll-target="#the-binomial-distribution"><span class="header-section-number">2.1</span> The Binomial distribution</a>
  <ul class="collapse">
<li><a href="#bernoulli-trials" id="toc-bernoulli-trials" class="nav-link" data-scroll-target="#bernoulli-trials"><span class="header-section-number">2.1.1</span> Bernoulli trials</a></li>
  <li><a href="#the-binomial-distribution-1" id="toc-the-binomial-distribution-1" class="nav-link" data-scroll-target="#the-binomial-distribution-1"><span class="header-section-number">2.1.2</span> The binomial distribution</a></li>
  <li><a href="#binomial-distributions-by-hand" id="toc-binomial-distributions-by-hand" class="nav-link" data-scroll-target="#binomial-distributions-by-hand"><span class="header-section-number">2.1.3</span> Binomial distributions by hand</a></li>
  <li><a href="#binomial-distributions-in-r" id="toc-binomial-distributions-in-r" class="nav-link" data-scroll-target="#binomial-distributions-in-r"><span class="header-section-number">2.1.4</span> Binomial distributions in R</a></li>
  </ul>
</li>
  <li>
<a href="#the-poisson-distribution" id="toc-the-poisson-distribution" class="nav-link" data-scroll-target="#the-poisson-distribution"><span class="header-section-number">2.2</span> The Poisson distribution</a>
  <ul class="collapse">
<li><a href="#poisson-distributions-by-hand" id="toc-poisson-distributions-by-hand" class="nav-link" data-scroll-target="#poisson-distributions-by-hand"><span class="header-section-number">2.2.1</span> Poisson distributions by hand</a></li>
  <li><a href="#poisson-distributions-in-r" id="toc-poisson-distributions-in-r" class="nav-link" data-scroll-target="#poisson-distributions-in-r"><span class="header-section-number">2.2.2</span> Poisson distributions in R</a></li>
  </ul>
</li>
  <li><a href="#the-poisson-approximation-of-the-binomial-model" id="toc-the-poisson-approximation-of-the-binomial-model" class="nav-link" data-scroll-target="#the-poisson-approximation-of-the-binomial-model"><span class="header-section-number">2.3</span> The Poisson approximation of the binomial model</a></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions"><span class="header-section-number">2.4</span> Conclusions</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-P2" class="quarto-section-identifier"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Binomial and Poisson Distributions</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p>The role of statisticians is often to determine the probability of events occurring in nature given our current understanding of the processes that are involved (normally on the basis of previous data). This requires a mathematical description of a theoretical relationship. We refer to this as a statistical model. Statistical models are like any model in that they can be a useful simplification of reality. However, as George Box said, ‘all models are wrong but some are useful’. We will come back to this concept again and again throughout this course.</p>
<p>Two models, the binomial and Poisson distributions, often provide excellent approximations of real-world events. This means that they can be used to determine the likelihood of events or series of events given certain ‘reasonable’ assumptions. In terms of planning, e.g.&nbsp;in the insurance industry, this is extremely useful.</p>
<p>Examples of the questions addressed using the binomial and Poisson models include:</p>
<ul>
<li>How likely is it that four hurricanes hit the US in a single season based on historic data?</li>
<li>How likely is it that a ‘50-year’ wave will hit in the next ten years? A 50 year wave is one of such size that it only occurs, on average, once in 50 years.</li>
<li>Is a river flooding now more than it used to? Is there a change in flooding frequency?</li>
<li>What proportion of clutches of fish eggs will contain all males?</li>
</ul>
<p>This practical gives you the opportunity to practice using these distributions. In the first part of this class you will conduct a number of short exercises to familiarize yourselves with the necessary commands in R to study probability using the binomial and Poisson distributions.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<section id="the-binomial-distribution" class="level2" data-number="2.1"><h2 data-number="2.1" class="anchored" data-anchor-id="the-binomial-distribution">
<span class="header-section-number">2.1</span> The Binomial distribution</h2>
<section id="bernoulli-trials" class="level3" data-number="2.1.1"><h3 data-number="2.1.1" class="anchored" data-anchor-id="bernoulli-trials">
<span class="header-section-number">2.1.1</span> Bernoulli trials</h3>
<p>A Bernoulli trial is a single event with a <em>binary</em> outcome (i.e., a success or a failure). Binary outcomes include:</p>
<ul>
<li>Alive / dead</li>
<li>Pregnant / not pregnant</li>
<li>Guilty / not guilty</li>
<li>Heads / tails</li>
<li>Win / lose</li>
</ul>
<p>Things that can have more than two outcomes can be re-coded into two categories. This concept can be extended to numerous situations, such as:</p>
<ul>
<li>Income greater than £100,000 vs.&nbsp;less than £100,000</li>
<li>Flower colour (blue vs.&nbsp;not blue; red vs.&nbsp;not red)</li>
</ul>
<p>by definition, each Bernoulli trial is independent of all previous trials.</p>
<p><em>Q28. If you tossed a fair coin 99 times and each time it landed heads, what is the probability of obtaining a head on the next toss of the coin?</em></p>
<p>This is a different question from asking whether 100 heads or (99 heads + 1 tails) is more likely in a throw of 100 coins. This is different because these events are independent.</p>
</section><section id="the-binomial-distribution-1" class="level3" data-number="2.1.2"><h3 data-number="2.1.2" class="anchored" data-anchor-id="the-binomial-distribution-1">
<span class="header-section-number">2.1.2</span> The binomial distribution</h3>
<p>The binomial distribution is a discrete probability distribution that applies to a series of Bernoulli trials. For example, if you had 10 eggs under a (big) chicken and they were all female, you might wonder how likely this was by chance. If this kept happening, you might question whether something was somehow making the eggs female. Here, the outcome can be female or male, and the trial size is 10 (each egg is a ‘trial’ with a binary outcome). You may question the assumption that the ratio female to male was 50:50 and favour an alternative hypothesis that the ratio was more female : less male. The binomial distribution allows you to quantify the probability of getting <span class="math inline">\(x\)</span> females from <span class="math inline">\(n\)</span> eggs for any given probability <span class="math inline">\(p=P(female)\)</span>. That is, we are not restricted to 50:50.</p>
<p>You need to know two things to use the binomial distribution. These are:</p>
<ul>
<li>the number of trials (<span class="math inline">\(n\)</span>, or sometimes <span class="math inline">\(k\)</span>)</li>
<li>probability of success (<span class="math inline">\(p\)</span>)</li>
</ul>
<p>From <em>p</em>, we can calculate the probability of failure as <span class="math inline">\(q = (1-p)\)</span>, since the two probabilities must sum to 1.</p>
<p>The distribution of a binomially distributed variable <span class="math inline">\(y\)</span> is specified <span class="math inline">\(y \sim Binom(n,p)\)</span>. We denote <span class="math inline">\(P(x)\)</span> as the probability of getting <span class="math inline">\(x\)</span> successes where <span class="math inline">\(x\)</span> is an integer <span class="math inline">\(0:n\)</span>.</p>
<p>The <strong>mean of a binomial distribution</strong> is <span class="math inline">\(n*p\)</span>. This gives you the <em>expected</em> outcome. For example, if <span class="math inline">\(P(female)=0.5\)</span> and <span class="math inline">\(n=10\)</span> eggs the expected number of females is <span class="math inline">\(10*0.5=5\)</span>.</p>
</section><section id="binomial-distributions-by-hand" class="level3" data-number="2.1.3"><h3 data-number="2.1.3" class="anchored" data-anchor-id="binomial-distributions-by-hand">
<span class="header-section-number">2.1.3</span> Binomial distributions by hand</h3>
<p>Wongles always lay two eggs in a clutch but 50% of the eggs are infertile and don’t hatch. We are interested in the proportions that we can expect to hatch from one clutch (two eggs).</p>
<p><em>Q29. What is the event here?</em></p>
<p><em>Q30. What is the probability of success?</em></p>
<p><em>Q31. What is the number of trials?</em></p>
<p><em>Q32. How many possible outcomes are there and what are they?</em></p>
<p><em>Q33. Write down the model specification in the standard notation (with parameters)</em></p>
<p><em>Q34. Calculate the expected proportions of clutches of eggs that contain (a) two fertile, (b) two infertile, and (c) one of each.</em></p>
<p>Often we are faced with more than two events and the quadratic expansion approach you used above is no longer convenient. In such circumstances you use the binomial expression.</p>
<p><em>Q35. Using the binomial probability mass function from</em> <a href="P7_appendix.html"><span>Chapter&nbsp;7</span></a><em>, calculate the fertility proportions for two eggs (Q34 a, b, c).</em></p>
<p>Oozle birds are much more sensible than Wongles and always have broods of eight offspring and all of them hatch. We are interested in modelling the probabilities of the proportion of male and female offspring in broods of eight eggs.</p>
<p><em>Q36. What is the Bernoulli event here? (What has two mutually exclusive outcomes?)</em></p>
<p><em>Q37. What are the theoretical limits to your outcomes (i.e, max numbers of each)?</em></p>
<p><em>Q38. What are the possible outcomes, and what is the total number of possible outcomes?</em></p>
<p><em>Q39. Write down the model for Oozle egg sex (</em><span class="math inline">\(y \sim Binom(n,p)\)</span><em>).</em></p>
<p>We will assume that the probability (<span class="math inline">\(p\)</span>) of any offspring being female is 0.5 and being male (<span class="math inline">\(q\)</span>) is 0.5. For the extreme cases where all offspring are one sex, we can use simple probability theory: the probability of getting <span class="math inline">\(n\)</span> females in a brood of size <span class="math inline">\(n\)</span> is equal to <span class="math inline">\(p^n\)</span>.</p>
<p><em>Q40. Calculate the probability of obtaining eight male offspring.</em></p>
<p><em>Q41. What is the mean number of females you would expect in Oozle broods?</em></p>
<p>It gets more complicated when you want to know the probability of getting, say, 1 male and 7 females from your clutch of eight eggs.</p>
<p><em>Q42. Given that</em> <span class="math inline">\(p=q\)</span><em>, what shape would expect the distribution to be?</em></p>
<p><em>Q43. Use the binomial expression to calculate the probability of obtaining 0, 1, 2, 3, 4, 5, 6, 7 and 8 male offspring (note that the distribution is symmetrical).</em></p>
<p>It is much easier, of course, to do this using R.</p>
</section><section id="binomial-distributions-in-r" class="level3" data-number="2.1.4"><h3 data-number="2.1.4" class="anchored" data-anchor-id="binomial-distributions-in-r">
<span class="header-section-number">2.1.4</span> Binomial distributions in R</h3>
<p>You can get probabilities for specific outcomes from a massive array of theoretical probability distributions from R. The binomial is just one of them.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">num_female</span> <span class="op">&lt;-</span> <span class="fl">4</span> <span class="co"># note that 4 is assigned to the variable called num_female</span></span>
<span><span class="va">num_trials</span> <span class="op">&lt;-</span> <span class="fl">8</span></span>
<span><span class="va">p_female</span> <span class="op">&lt;-</span> <span class="fl">0.5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># for a single probability: y~Binom(n=8, p=0.5) determine P(y_i=4)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span><span class="va">num_female</span>, <span class="va">num_trials</span>, <span class="va">p_female</span><span class="op">)</span> <span class="co"># dbinom(4, 8, 0.5)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># formatted output just because:</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"P("</span>, <span class="va">num_female</span>, <span class="st">" female | "</span>, <span class="va">num_trials</span>, <span class="st">" eggs) = "</span>,</span>
<span>       <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span><span class="va">num_female</span>, <span class="va">num_trials</span>, <span class="va">p_female</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "P(4 female | 8 eggs) = 0.2734375"</code></pre>
</div>
</div>
<p>Often we want to know cumulative probabilities. This allows us to answer questions like ‘what is the probability of obtaining &lt; 4 females in a brood of 8 eggs?’ Here, &lt;4 equates to the cumulative probability P(0) + P(1) + P(2) + P(3).</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># pbinom gives the cumulative probability</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"The cumulative probability is"</span>, </span>
<span>      <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">pbinom</a></span><span class="op">(</span><span class="fl">0</span><span class="op">:</span><span class="va">num_female</span> <span class="op">-</span> <span class="fl">1</span>, <span class="va">num_trials</span>, <span class="va">p_female</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The cumulative probability is 0.36328125"</code></pre>
</div>
</div>
<p><em>Q44. Why do we parameterise <code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code> with <code>num_female-1</code> rather than <code>num_female</code>?</em></p>
<p><em>Q45. Would this change if the question was</em> <span class="math inline">\(P( \leq 4)\)</span><em>?</em></p>
<p><em>Q46. Take the ’max’ out of the above line and run again. You should see 5 cumulative probabilities. Why is the first cumulative probability zero?</em></p>
<p><em>Q47. Calculate P(&lt; 4 females | 8 eggs) using <code><a href="https://rdrr.io/r/stats/Binomial.html">dbinom()</a></code> instead of <code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code>.</em></p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># You can check what R is doing by running parts of code:</span></span>
<span><span class="fl">0</span><span class="op">:</span><span class="va">num_female</span> <span class="op">-</span> <span class="fl">1</span> <span class="co"># Oops! Is this what you expected?</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1  0  1  2  3</code></pre>
</div>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fl">0</span><span class="op">:</span><span class="op">(</span><span class="va">num_female</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span> <span class="co"># this is actually what we want.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0 1 2 3</code></pre>
</div>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Correct the code above. Why did this bug have no effect?</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>Q48. What is the probability of getting 3 females?</em></p>
<p><em>Q49. What is the probability of getting 8 females?</em></p>
<p><em>Q50. What cumulative probabilities would you need to consider to answer the question ‘What is the probability of getting fewer than three females?’</em></p>
<p><em>Q51. Write down the model that describes this random process (number of females per eight eggs). Your answer should be like this:</em> <span class="math inline">\(y \sim Binom(n, p)\)</span><em>.</em></p>
<p><em>Q52. What is the probability of getting &lt; 4 females?</em></p>
<p><em>Q53. What is the probability of getting</em> <span class="math inline">\(\leq\)</span> 4 females?</p>
<p><em>Q54. What is the probability of getting &gt; than 8 females?</em></p>
<p><em>Q55. What is the probability of getting</em> <span class="math inline">\(\geq\)</span> than 2 females?</p>
<p>Let’s visualize these distributions in order to better understand them.</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Run this, then explore values of p_female</span></span>
<span><span class="co"># Note: 'success' and 'failure' is arbitrary. Just make sure you're calculating</span></span>
<span><span class="co"># what you think. How would you calculate the probabilities for males instead?</span></span>
<span><span class="va">num_female</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">8</span><span class="op">)</span> </span>
<span><span class="va">p_female</span> <span class="op">&lt;-</span> <span class="fl">0.5</span> <span class="co"># what are the limits of p_female?</span></span>
<span><span class="va">prFemale_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>num_female <span class="op">=</span> <span class="va">num_female</span>, </span>
<span>                          prob <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span><span class="va">num_female</span>, <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">num_female</span><span class="op">)</span>, <span class="va">p_female</span><span class="op">)</span><span class="op">)</span> </span>
<span><span class="va">prFemale_df</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  num_female       prob
1          0 0.00390625
2          1 0.03125000
3          2 0.10937500
4          3 0.21875000
5          4 0.27343750
6          5 0.21875000
7          6 0.10937500
8          7 0.03125000
9          8 0.00390625</code></pre>
</div>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span><span class="op">(</span><span class="va">prFemale_df</span><span class="op">$</span><span class="va">prob</span>, names <span class="op">=</span> <span class="va">prFemale_df</span><span class="op">$</span><span class="va">num_female</span>, </span>
<span>        xlab <span class="op">=</span> <span class="st">"Number of females"</span>, ylab <span class="op">=</span> <span class="st">"Probability"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-binom_dist" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="P2_binomial_poisson_files/figure-html/fig-binom_dist-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption class="figure-caption">Figure&nbsp;2.1: Binomial probability distribution</figcaption></figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">prFemale_df</span><span class="op">$</span><span class="va">cumul_prob</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cumsum.html">cumsum</a></span><span class="op">(</span><span class="va">prFemale_df</span><span class="op">$</span><span class="va">prob</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span><span class="op">(</span><span class="va">prFemale_df</span><span class="op">$</span><span class="va">cumul_prob</span>, names <span class="op">=</span> <span class="va">prFemale_df</span><span class="op">$</span><span class="va">num_female</span>, </span>
<span>        xlab <span class="op">=</span> <span class="st">"Enter the correct label!"</span>, ylab <span class="op">=</span> <span class="st">"Enter the correct label!"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-binom_cum_dist" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="P2_binomial_poisson_files/figure-html/fig-binom_cum_dist-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption class="figure-caption">Figure&nbsp;2.2: Cumulative binomial probability distribution</figcaption></figure>
</div>
</div>
</div>
<p>Try re-plotting so that the two panels appear side by side (hint: <code>par(mfrow=c(...))</code>).</p>
<p>Note <span class="math inline">\(P(y_i=x)\)</span> is read as ‘the probability that a random observation <span class="math inline">\(y_i\)</span> equals <span class="math inline">\(x\)</span>’. Sometimes this includes conditions: <span class="math inline">\(P(y_i=x|n,p)\)</span>, which is read as the probability that <span class="math inline">\(y_i\)</span> equals <span class="math inline">\(x\)</span> given <span class="math inline">\(n\)</span> and <span class="math inline">\(p\)</span>. You may see <span class="math inline">\(P()\)</span>, <span class="math inline">\(Pr()\)</span>, <span class="math inline">\(p()\)</span>, or <span class="math inline">\(Prob()\)</span>, which all mean the same thing.</p>
<p>The interpretation of <span class="math inline">\(P(y_i=8\ |\ n=8,\ p=0.5) = 0.00391\)</span> is that the probability of 8 female offspring in a clutch of 8 eggs is 0.00391.</p>
<p>In other words, if we have 500 broods, each with 8 eggs, we expect <span class="math inline">\(500 * 0.00391 = 1.95 \approx 2\)</span> broods to be all female. Is there something strange about our Oozle or is it just one of the 2/500 by chance?</p>
<p><em>Q56. Why is a bar graph the appropriate plot here?</em></p>
<p><em>Q57. What do you notice about the shape of the distribution when</em> <span class="math inline">\(p=q=0.5\)</span>?</p>
<p><em>Q58. Re-run the analysis with the probability of female as 0.8. Plot the results.</em></p>
<p><em>Q59. What is the shape of the distribution now?</em></p>
<hr></section></section><section id="the-poisson-distribution" class="level2" data-number="2.2"><h2 data-number="2.2" class="anchored" data-anchor-id="the-poisson-distribution">
<span class="header-section-number">2.2</span> The Poisson distribution</h2>
<p>The Poisson distribution is another probability distribution that describes discrete events that occur in space and/or time. The Poisson distribution is used to model (predict) the distribution of events that are rare, random, and independent. This can include events like earthquakes, storms, or the number of bends arriving at the SAMS recompression facility.</p>
<p>The Poisson distribution takes a single parameter: the mean. If a variable is Poisson distributed, its variance will equal its mean. This is a diagnostic feature of the distribution. The Poisson distribution is a discrete probability distribution, but its parameter, the mean, is continuous (similar to continuous <span class="math inline">\(p\)</span> for the discrete binomial distribution).</p>
<p>The Poisson formula is simple - find it in <a href="P7_appendix.html"><span>Chapter&nbsp;7</span></a> . Here, <span class="math inline">\(\bar{y}\)</span> is the mean, <span class="math inline">\(x\)</span> is the outcome of interest, <span class="math inline">\(e\)</span> is Euler’s number, and <span class="math inline">\(!\)</span> is factorial. Note that here, we use <span class="math inline">\(\bar{y}\)</span> as our stand-in for the population parameter <span class="math inline">\(\lambda = \mu = \sigma\)</span> which defines the poisson distribution. Translate this formula into an R function by completing this code:</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># hint: exp(2) = e^2</span></span>
<span><span class="co"># hint: factorial(3) = 3!</span></span>
<span><span class="va">calc_poisson_prob</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span>, <span class="va">y_bar</span><span class="op">)</span> <span class="op">{</span></span>
<span>  </span>
<span><span class="op">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="poisson-distributions-by-hand" class="level3" data-number="2.2.1"><h3 data-number="2.2.1" class="anchored" data-anchor-id="poisson-distributions-by-hand">
<span class="header-section-number">2.2.1</span> Poisson distributions by hand</h3>
<p>These problems usually start by asking you to calculate the mean number of observations made per unit of space or time. This is the Poisson parameter, and is referred to as the <em>rate</em> or as <em>lambda</em> (<span class="math inline">\(\lambda\)</span>). The unit could be spatial (e.g., per <span class="math inline">\(m^2\)</span>) or temporal (e.g., per hour).</p>
<p>Consider randomly throwing a 1<span class="math inline">\(m^2\)</span> quadrat repeatedly on a sandy beach covered in worm casts <a href="#fig-wormcasts">Figure&nbsp;<span>2.3</span></a>. You then count the number of casts in each quadrat.</p>
<div id="fig-wormcasts" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="figs/worm_casts.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;2.3: Worm casts on a sandy beach with 1x1 m quadrats.</figcaption></figure>
</div>
<p>From these data you can calculate the mean number of observations per unit.</p>
<p>The code below generates a dataframe from which you can determine that the mean number of worms per quadrat is 1.41. We wish to predict the proportion of quadrats that would contain 0, 1, 2, 3, 4, and 5 worms, assuming that the worms are independently distributed across space (i.e., random: one worm’s location has no effect on another worm’s location, and there is no relevant environmental variation).</p>
<p>We thus wish to determine the probability of observing our data assuming that the worms casts are randomly distributed. To do this, we need to know the probability of observing each count (zero to infinity), given the mean count per quadrat.</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># num_worms is the number of worms per quadrat</span></span>
<span><span class="co"># num_quadrats is numbers of quadrats observed containing that number of worms</span></span>
<span><span class="co"># this dataset is summarised. Raw data might have columns: quadrat_id, num_worms</span></span>
<span><span class="va">worm_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>num_worms <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">3</span>, <span class="fl">4</span>, <span class="fl">5</span>, <span class="fl">6</span><span class="op">)</span>,</span>
<span>                      num_quadrats <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">35</span>, <span class="fl">28</span>, <span class="fl">15</span>, <span class="fl">10</span>, <span class="fl">7</span>, <span class="fl">5</span>, <span class="fl">0</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">worm_df</span> <span class="co"># display dataframe</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  num_worms num_quadrats
1         0           35
2         1           28
3         2           15
4         3           10
5         4            7
6         5            5
7         6            0</code></pre>
</div>
</div>
<p>As the number of worms per quadrat is low compared to the number of worms that could exist within a quadrat we consider these are rare events and hence can be reasonably described by a Poisson distribution (assuming worms occur independently).</p>
<p>From just the mean, we can calculate the expected frequency of observing different numbers of worms in any quadrat (assuming the model assumptions are met - remind yourself what these assumptions are). The number of worms per quadrat (<span class="math inline">\(y\)</span>) is discrete; it can only take integers greater or equal to zero.</p>
<p>Probability questions often includes terms such as <span class="math inline">\(P(y_i \leq a)\)</span>. That is, the probability that an observation <span class="math inline">\(i\)</span> of the random variable <span class="math inline">\(y\)</span> is less than or equal to <span class="math inline">\(a\)</span>. For example, in this context you might get asked for <span class="math inline">\(P(y_i \leq 1)\)</span> which asks what is the probability of a random quadrat being thrown (<span class="math inline">\(y_i\)</span>) containing 1 or fewer worm casts (<span class="math inline">\(a\)</span>, an integer value). To be fully complete, we might even write <span class="math inline">\(P(y_i \leq 1 | \lambda)\)</span>, which acknowledges that we know the (sample) mean.</p>
<p>So, if you are interested in predicting the probability of obtaining 1 or fewer worms per quadrat, you would start your calculation by writing <span class="math inline">\(P(y_i = 0) + P(y_i=1) = \dots\)</span>.</p>
<p><em>Q60. Use your <code>calc_poisson_prob()</code> function to calculate the expected frequency of 0, 1 &amp; 2 worms per quadrat.</em></p>
<p><em>Q61. What calculation would you need to conduct to determine</em> <span class="math inline">\(P(y_i \geq 1)\)</span><em>?</em></p>
<p>R has built-in functions for calculating these, but it is important to know what you are asking them to calculate.</p>
</section><section id="poisson-distributions-in-r" class="level3" data-number="2.2.2"><h3 data-number="2.2.2" class="anchored" data-anchor-id="poisson-distributions-in-r">
<span class="header-section-number">2.2.2</span> Poisson distributions in R</h3>
<p>You can determine the expected probabilities for each worm count per quadrat once you have determined the mean count of worms per quadrat. Since we have a summarised dataset (i.e., the number of observations <code>num_quadrats</code> for each number of worms <code>num_worms</code>, rather than the raw data with a row for each quadrat), we need to do some calculations. The mean number of worms per quadrat = (total number of worms) / (total number of quadrats).</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">worm_df</span><span class="op">$</span><span class="va">num_quadrats</span><span class="op">)</span> <span class="co"># total number of quadrats</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 100</code></pre>
</div>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lambda_worms</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/with.html">with</a></span><span class="op">(</span><span class="va">worm_df</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">num_worms</span> <span class="op">*</span> <span class="va">num_quadrats</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">num_quadrats</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">lambda_worms</span> <span class="co"># the mean worms per quadrat"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.41</code></pre>
</div>
</div>
<p>Given this, we can find <span class="math inline">\(P(y_i \leq 5)\)</span> (that is, the probability of a random quadrat (<span class="math inline">\(y_i\)</span>) containing five or fewer worms). With a mean of 1.41 worms per quadrat, <span class="math inline">\(P(y_i \leq 5) = 0.997\)</span> (3 sf). This means that, if your data are Poisson distributed, it is highly likely that there will be fewer than five worms in your quadrat if <span class="math inline">\(\lambda = 1.41\)</span>.</p>
<p><em>Q62. If the mean number of worms was 3 per quadrat, would you be more or less likely to get five worms in your quadrat?</em></p>
<p>To do this in R, we use <code><a href="https://rdrr.io/r/stats/Poisson.html">dpois()</a></code> and <code><a href="https://rdrr.io/r/stats/Poisson.html">ppois()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># ?dpois </span></span>
<span><span class="co"># for questions like 'determine P(y_i=a | lambda)'</span></span>
<span><span class="va">a</span> <span class="op">&lt;-</span> <span class="fl">5</span> </span>
<span><span class="va">lambda</span> <span class="op">&lt;-</span> <span class="fl">1.41</span> </span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/Poisson.html">dpois</a></span><span class="op">(</span><span class="va">a</span>, <span class="va">lambda</span><span class="op">)</span> <span class="co"># probability of observing 'a' worms per quadrat: dpois()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01133859</code></pre>
</div>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># ?ppois</span></span>
<span><span class="co"># for questions like 'determine P(y_i &gt;= a | lambda)</span></span>
<span><span class="fl">1</span><span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/stats/Poisson.html">ppois</a></span><span class="op">(</span><span class="va">a</span><span class="op">-</span><span class="fl">1</span>, <span class="va">lambda</span><span class="op">)</span> <span class="co"># probability of observing &gt;= 'a' worms: ppois()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01465169</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Poisson.html">ppois</a></span><span class="op">(</span><span class="fl">0</span><span class="op">:</span><span class="va">a</span>, <span class="va">lambda</span><span class="op">)</span> <span class="co"># what does 0:a mean? What's another way to do this? </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2441433 0.5883853 0.8310759 0.9451405 0.9853483 0.9966869</code></pre>
</div>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">signif</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Poisson.html">ppois</a></span><span class="op">(</span><span class="fl">0</span><span class="op">:</span><span class="va">a</span>, <span class="va">lambda</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span> <span class="co"># round with ?signif</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.244 0.588 0.831 0.945 0.985 0.997</code></pre>
</div>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Poisson.html">dpois</a></span><span class="op">(</span><span class="fl">0</span><span class="op">:</span><span class="va">a</span>, <span class="va">lambda</span><span class="op">)</span>,</span>
<span>        ylab <span class="op">=</span> <span class="st">"Probability"</span>, xlab <span class="op">=</span> <span class="st">"Number of worms"</span>,</span>
<span>        space <span class="op">=</span> <span class="fl">0.2</span>, ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">0.5</span><span class="op">)</span>, names.arg <span class="op">=</span> <span class="fl">0</span><span class="op">:</span><span class="va">a</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-worm_poisson" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="P2_binomial_poisson_files/figure-html/fig-worm_poisson-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;2.4: Poisson probability distribution.</figcaption></figure>
</div>
</div>
</div>
<p>Now change the plot so that the cumulative probabilities are plotted. You will need to change the code to use <code><a href="https://rdrr.io/r/stats/Poisson.html">ppois()</a></code> instead of <code><a href="https://rdrr.io/r/stats/Poisson.html">dpois()</a></code>, as well as the y-axis limits (<code>ylim</code>).</p>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># create new columns in worm_df for the probabilities</span></span>
<span><span class="va">worm_df</span><span class="op">$</span><span class="va">prob</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Poisson.html">dpois</a></span><span class="op">(</span><span class="va">worm_df</span><span class="op">$</span><span class="va">num_worms</span>, <span class="va">lambda</span><span class="op">)</span></span>
<span><span class="va">worm_df</span><span class="op">$</span><span class="va">cumul_prob</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cumsum.html">cumsum</a></span><span class="op">(</span><span class="va">worm_df</span><span class="op">$</span><span class="va">prob</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Make Table 2.1. Use packageName::function() instead of loading with library()</span></span>
<span><span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="va">worm_df</span>, digits<span class="op">=</span><span class="fl">5</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-worm_table" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2.1: Worm cast observations and expected probabilities.</caption>
<thead><tr class="header">
<th style="text-align: right;">num_worms</th>
<th style="text-align: right;">num_quadrats</th>
<th style="text-align: right;">prob</th>
<th style="text-align: right;">cumul_prob</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">0.24414</td>
<td style="text-align: right;">0.24414</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">0.34424</td>
<td style="text-align: right;">0.58839</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0.24269</td>
<td style="text-align: right;">0.83108</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.11406</td>
<td style="text-align: right;">0.94514</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.04021</td>
<td style="text-align: right;">0.98535</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.01134</td>
<td style="text-align: right;">0.99669</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00266</td>
<td style="text-align: right;">0.99935</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><em>Q64. Format the probabilities in the table to 3 decimal places.</em></p>
<p>If individual probability values (not cumulative probability) are multiplied by the total number of quadrats thrown (100), we generate the expected frequency distribution for comparison with the observed results above.</p>
<p><em>Q65. Write the appropriate code to add a column(called <code>num_quadrats_expected</code>) to ‘worm_df’ that is the expected number of quadrats (given 100 quadrats total).</em></p>
<p>This is the number of quadrats that you would expect to contain 0, 1, …, 5 worms, given that the mean density of worms is 1.41 per m<span class="math inline">\(^2\)</span>. Note that the number of worms per quadrat is a discrete variable, but you can have non-integer ‘expectations’ (i.e.&nbsp;means).</p>
<p><em>Q66. Add another column that is the difference in the observed number of quadrats and <code>num_quadrats_expected</code>.</em></p>
<p><em>Q67. Produce a bar graph of this difference.</em></p>
<hr></section></section><section id="the-poisson-approximation-of-the-binomial-model" class="level2" data-number="2.3"><h2 data-number="2.3" class="anchored" data-anchor-id="the-poisson-approximation-of-the-binomial-model">
<span class="header-section-number">2.3</span> The Poisson approximation of the binomial model</h2>
<p>Where the number of trials is large and the probability of success is small, the Poisson distribution can be used as an approximation of the binomial distribution. Under these circumstances you can calculate the mean of a variable that has a binomial distribution (number of trials x probability of success; <span class="math inline">\(n*p\)</span>) and use that as an estimate of <span class="math inline">\(\lambda\)</span> in the Poisson model. The reason why you may wish to do this is because the Poisson model is much easier to use than the binomial model when <span class="math inline">\(n\)</span> is large.</p>
<p>There are several rules of thumb that apply here. Some say that when <span class="math inline">\(p&lt;0.1\)</span>, the Poisson approximation may be preferable to the binomial, other texts state that <span class="math inline">\(n\)</span> should be &gt; 50 and <span class="math inline">\(p&lt;0.05\)</span> (so <span class="math inline">\(n * p = \lambda = 2.5\)</span>) whilst others state <span class="math inline">\(n&gt;100\)</span> and <span class="math inline">\(n*p&lt;10\)</span>. The point is that as <span class="math inline">\(n\)</span> increases and <span class="math inline">\(p\)</span> decreases, the approximation gets better.</p>
<p>There are an infinite number of ways of multiplying two numbers together to get 5. Call our numbers <span class="math inline">\(p\)</span> and <span class="math inline">\(k\)</span>. For example, when <span class="math inline">\(p=0.5\)</span>, <span class="math inline">\(n=10\)</span> OR when <span class="math inline">\(p=0.05\)</span>, <span class="math inline">\(n=100\)</span>, <span class="math inline">\(n*p=5\)</span>. We can use this to illustrate the Poisson approximation of the binomial distribution.</p>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># generate dataframe with probability for 0:16 'successes' from different </span></span>
<span><span class="co"># distributions but where mean is 5.</span></span>
<span><span class="co"># note that in y ~ Binom(10,0.5), probability of &gt;10 successes is zero.</span></span>
<span><span class="co"># We're going to leverage the power of the tidyverse here</span></span>
<span><span class="va">y_seq</span> <span class="op">&lt;-</span> <span class="fl">0</span><span class="op">:</span><span class="fl">16</span></span>
<span><span class="va">binom_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>y<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="va">y_seq</span>, times<span class="op">=</span><span class="fl">3</span><span class="op">)</span>, <span class="co"># ?rep</span></span>
<span>                   n<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">10</span>, <span class="fl">20</span>, <span class="fl">100</span><span class="op">)</span>, each<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">y_seq</span><span class="op">)</span><span class="op">)</span>,</span>
<span>                   p<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.5</span>, <span class="fl">0.25</span>, <span class="fl">0.05</span><span class="op">)</span>, each<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">y_seq</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>mean<span class="op">=</span><span class="va">n</span><span class="op">*</span><span class="va">p</span>,</span>
<span>           prob<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span><span class="va">y_seq</span>, <span class="va">n</span>, <span class="va">p</span><span class="op">)</span>,</span>
<span>           label<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"y ~ Binom("</span>, <span class="va">n</span>, <span class="st">", "</span>, <span class="va">p</span>, <span class="st">")"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">pois_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>y<span class="op">=</span><span class="va">y_seq</span>,</span>
<span>                  n<span class="op">=</span><span class="cn">NA</span>, </span>
<span>                  p<span class="op">=</span><span class="cn">NA</span>,</span>
<span>                  mean<span class="op">=</span><span class="fl">5</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>prob<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/stats/Poisson.html">dpois</a></span><span class="op">(</span><span class="va">y_seq</span>, <span class="va">mean</span><span class="op">)</span>,</span>
<span>           label<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"y ~ Pois("</span>, <span class="va">mean</span>, <span class="st">")"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">PDF_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind_rows.html">bind_rows</a></span><span class="op">(</span><span class="va">binom_df</span>, <span class="va">pois_df</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>label<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">label</span>, levels<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">label</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">binom_df</span>, <span class="fl">2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
      y     n     p  mean     prob label             
  &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;             
1     0    10   0.5     5 0.000977 y ~ Binom(10, 0.5)
2     1    10   0.5     5 0.00977  y ~ Binom(10, 0.5)</code></pre>
</div>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">pois_df</span>, <span class="fl">2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
      y n     p      mean    prob label      
  &lt;int&gt; &lt;lgl&gt; &lt;lgl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      
1     0 NA    NA        5 0.00674 y ~ Pois(5)
2     1 NA    NA        5 0.0337  y ~ Pois(5)</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">PDF_df</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">y</span>, <span class="va">prob</span>, fill<span class="op">=</span><span class="va">label</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>  <span class="co"># ggplot(data, aes(xVar, yVar))</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span>stat<span class="op">=</span><span class="st">"identity"</span>, position<span class="op">=</span><span class="st">"dodge"</span>, colour<span class="op">=</span><span class="st">"grey30"</span><span class="op">)</span> <span class="op">+</span>  <span class="co"># ?geom_bar</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_brewer.html">scale_fill_brewer</a></span><span class="op">(</span><span class="st">"Distribution"</span>, palette<span class="op">=</span><span class="st">"Purples"</span><span class="op">)</span> <span class="op">+</span> <span class="co"># from colorbrewer2.org</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x<span class="op">=</span><span class="st">"Number of successes with mean = 5"</span>, y<span class="op">=</span><span class="st">"Probability"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>legend.position<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.85</span>, <span class="fl">0.85</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-binom_pois_approx" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="P2_binomial_poisson_files/figure-html/fig-binom_pois_approx-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption class="figure-caption">Figure&nbsp;2.5: Binomial and Poisson distributions converge with larger numbers of events, depending on p.</figcaption></figure>
</div>
</div>
</div>
<p><em>Q68. What is the modal value in these distributions?</em></p>
<p>Generate some random numbers from the distributions in <a href="#fig-binom_pois_approx">Figure&nbsp;<span>2.5</span></a> and calculate their mean and variance. Here is <span class="math inline">\(y \sim Pois(\lambda=5)\)</span>:</p>
<div class="cell">
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Poisson.html">rpois</a></span><span class="op">(</span><span class="fl">10000</span>, <span class="fl">5</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"Mean: "</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">signif</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span>, <span class="st">", variance: "</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">signif</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">var</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Mean: 5.01, variance: 4.97"</code></pre>
</div>
</div>
<p><em>Q69. What do you notice about the mean and variance in the Poisson model?</em></p>
<p><em>Q70. What do you notice about the mean and variance in the binomial models as</em> <span class="math inline">\(n\)</span> <em>increases and</em> <span class="math inline">\(p\)</span> <em>decreases? When is it more similar to the Poisson? Is this what you expected?</em></p>
<hr></section><section id="conclusions" class="level2" data-number="2.4"><h2 data-number="2.4" class="anchored" data-anchor-id="conclusions">
<span class="header-section-number">2.4</span> Conclusions</h2>
<p>The binomial distribution is a discrete probability distribution that models situations where the outcome of an observation or experiment is binary (i.e., two possibilities) or can be coded as such. The binomial model enables us to predict the probability of making our observation or series of independent observations for any given probability of a success (<span class="math inline">\(p\)</span>). This enables us to quantify how likely our observation is to have occurred, by chance. If the chance of our observation is very low, we can challenge the hypothesis with regard the probability of success (<span class="math inline">\(p\)</span>) and suggest a different value.</p>
<p>The Poisson distribution is another discrete probability distribution that is used to predict the chance occurrence of observations that are rare, independent and randomly distributed with mean = variance = <span class="math inline">\(\lambda\)</span>. The Poisson distribution can be used as an approximation of the binomial distribution where the number of trials (<span class="math inline">\(n\)</span>) is large and the probability of success (<span class="math inline">\(p\)</span>) is small. This approximation is useful as, unlike the Poisson distribution, the binomial calculation requires the handling of massive numbers (from large factorials).</p>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./P1_R_recap.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">R recap</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./P3_normal.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Normal distribution</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>