<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>H2 Data Science Practicals - 3&nbsp; Normal distribution</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./P4_t_CIs.html" rel="next">
<link href="./P2_binomial_poisson.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./P3_normal.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Normal distribution</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">H2 Data Science Practicals</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P0_R_setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R setup</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P1_R_recap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">R recap</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P2_binomial_poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Binomial and Poisson Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P3_normal.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Normal distribution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P4_t_CIs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">T distribution and confidence intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P5_ANOVA_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">ANOVA and regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P6_machine_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Machine Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P7_appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Appendix</span></span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#using-the-normal-probability-distributions" id="toc-using-the-normal-probability-distributions" class="nav-link active" data-scroll-target="#using-the-normal-probability-distributions"><span class="header-section-number">3.1</span> Using the normal probability distributions</a>
  <ul class="collapse">
<li><a href="#using-r-to-calculate-areas-under-the-normal-curve" id="toc-using-r-to-calculate-areas-under-the-normal-curve" class="nav-link" data-scroll-target="#using-r-to-calculate-areas-under-the-normal-curve"><span class="header-section-number">3.1.1</span> Using R to calculate areas under the normal curve</a></li>
  </ul>
</li>
  <li><a href="#normal-model-adequacy" id="toc-normal-model-adequacy" class="nav-link" data-scroll-target="#normal-model-adequacy"><span class="header-section-number">3.2</span> Normal model adequacy</a></li>
  <li><a href="#calculating-quantiles-in-the-normal-distribution" id="toc-calculating-quantiles-in-the-normal-distribution" class="nav-link" data-scroll-target="#calculating-quantiles-in-the-normal-distribution"><span class="header-section-number">3.3</span> Calculating quantiles in the normal distribution</a></li>
  <li><a href="#testing-for-normality" id="toc-testing-for-normality" class="nav-link" data-scroll-target="#testing-for-normality"><span class="header-section-number">3.4</span> Testing for normality</a></li>
  <li><a href="#transformations" id="toc-transformations" class="nav-link" data-scroll-target="#transformations"><span class="header-section-number">3.5</span> Data transformations</a></li>
  <li><a href="#functions-in-r" id="toc-functions-in-r" class="nav-link" data-scroll-target="#functions-in-r"><span class="header-section-number">3.6</span> Functions in R</a></li>
  <li>
<a href="#the-central-limit-theorem" id="toc-the-central-limit-theorem" class="nav-link" data-scroll-target="#the-central-limit-theorem"><span class="header-section-number">3.7</span> The central limit theorem</a>
  <ul class="collapse">
<li><a href="#the-distribution-of-means-from-various-data-distributions" id="toc-the-distribution-of-means-from-various-data-distributions" class="nav-link" data-scroll-target="#the-distribution-of-means-from-various-data-distributions"><span class="header-section-number">3.7.1</span> The distribution of means from various data distributions</a></li>
  </ul>
</li>
  <li><a href="#the-standard-error-of-the-mean" id="toc-the-standard-error-of-the-mean" class="nav-link" data-scroll-target="#the-standard-error-of-the-mean"><span class="header-section-number">3.8</span> The standard error of the mean</a></li>
  <li>
<a href="#normal-approximations-for-other-distributions" id="toc-normal-approximations-for-other-distributions" class="nav-link" data-scroll-target="#normal-approximations-for-other-distributions"><span class="header-section-number">3.9</span> Normal approximations for other distributions</a>
  <ul class="collapse">
<li><a href="#the-normal-approximation-of-the-poisson-distribution" id="toc-the-normal-approximation-of-the-poisson-distribution" class="nav-link" data-scroll-target="#the-normal-approximation-of-the-poisson-distribution"><span class="header-section-number">3.9.1</span> The Normal approximation of the Poisson distribution</a></li>
  <li><a href="#the-normal-approximation-of-the-binomial-distribution" id="toc-the-normal-approximation-of-the-binomial-distribution" class="nav-link" data-scroll-target="#the-normal-approximation-of-the-binomial-distribution"><span class="header-section-number">3.9.2</span> The Normal approximation of the binomial distribution</a></li>
  </ul>
</li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions"><span class="header-section-number">3.10</span> Conclusions</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-P3" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Normal distribution</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p>Statistical inference is the process by which we infer from a sample statistic to the population. We need to infer from samples to populations because it is usually impossible to measure the entire populations. We call this this estimating population parameters from samples.</p>
<p>In order to infer from samples to populations we need to understand/predict how the statistics we generate from our samples ‘behave’. To do this we use theoretical distributions.</p>
<p><em>Q71. Which two theoretical distributions have we already covered in this course?</em></p>
<p>The normal (a.k.a., Gaussian) distribution is another theoretical distribution and is central to inferential statistics. If your data (or, more accurately, statistics derived from you data) are reasonably approximated by the normal distribution then you will be able to use a wide range of techniques to deal with it.</p>
<p>In this practical we will examine the normal distribution, calculate Z scores, and interpret those Z scores. We’ll also use our knowledge of the normal distribution’s behaviour to produce confidence intervals and assess whether data are reasonably assumed to be normally distributed, transforming the data where they are not. We’ll apply the CLT and evaluate how well other distributions are approximated by the normal distribution.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://readxl.tidyverse.org">readxl</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<section id="using-the-normal-probability-distributions" class="level2" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="using-the-normal-probability-distributions">
<span class="header-section-number">3.1</span> Using the normal probability distributions</h2>
<p>The length, in cm, of a catch of herring was measured. Five hundred individuals were studied. We will consider this group to be the entire population of interest. The population parameters are: mean length 37.6 cm, standard deviation 1.20 cm.</p>
<p><em>Q72. What are the theoretical limits of the normal distribution?</em></p>
<p><em>Q73. Do you think normality a fair assumption for these data?</em></p>
<p><em>Q74. Assume length of herring is approximately normally distributed and write down the model which describes the fish length distribution (</em> <span class="math inline">\(y_i \sim Norm(\mu, \sigma)\)</span> <em>).</em></p>
<p>When we have population parameters such as we have here, we can calculate Z scores for individuals (or groups of individuals) from that population and calculate how unusual they are. For the moment, we are interested in determining what proportion of fish from this population are expected to be &lt; 38 cm.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mu</span> <span class="op">&lt;-</span> <span class="fl">37.6</span></span>
<span><span class="va">sigma</span> <span class="op">&lt;-</span> <span class="fl">1.2</span></span>
<span><span class="va">y</span> <span class="op">&lt;-</span> <span class="fl">38</span></span>
<span></span>
<span><span class="va">y_l38_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>len<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="va">mu</span><span class="op">-</span><span class="fl">3</span><span class="op">*</span><span class="va">sigma</span>, <span class="va">mu</span><span class="op">+</span><span class="fl">3</span><span class="op">*</span><span class="va">sigma</span>, length.out<span class="op">=</span><span class="fl">1e3</span><span class="op">)</span>,</span>
<span>                     density<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">dnorm</a></span><span class="op">(</span><span class="va">len</span>, <span class="va">mu</span>, <span class="va">sigma</span><span class="op">)</span>,</span>
<span>                     shade<span class="op">=</span><span class="va">len</span> <span class="op">&lt;</span> <span class="fl">38</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">y_l38_df</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">len</span>, ymin<span class="op">=</span><span class="fl">0</span>, ymax<span class="op">=</span><span class="va">density</span>, fill<span class="op">=</span><span class="va">shade</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_ribbon.html">geom_ribbon</a></span><span class="op">(</span>colour<span class="op">=</span><span class="st">"grey30"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"white"</span>, <span class="st">"red3"</span><span class="op">)</span>, guide<span class="op">=</span><span class="st">"none"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x<span class="op">=</span><span class="st">"Herring length (cm)"</span>, y<span class="op">=</span><span class="st">"density"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-normal_herring" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="P3_normal_files/figure-html/fig-normal_herring-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;3.1: Normal distribution of herring lengths.</figcaption></figure>
</div>
</div>
</div>
<section id="using-r-to-calculate-areas-under-the-normal-curve" class="level3" data-number="3.1.1"><h3 data-number="3.1.1" class="anchored" data-anchor-id="using-r-to-calculate-areas-under-the-normal-curve">
<span class="header-section-number">3.1.1</span> Using R to calculate areas under the normal curve</h3>
<p>To solve this problem using R we use the cumulative probability. Observations at the extreme low end are extremely unlikely, but the probability of observing data increases and reaches a maximum at the mean, after which it declines again. The normal distribution is symmetrical.</p>
<p><em>Q77. What shape is the cumulative probability curve of a normally distributed variable?</em></p>
<p>You can ask R to determine the probabilities of an event occurring within a normal distribution. For example, you could ask what the probability is of observing a fish greater than 38 cm, when the mean is 37.6 cm and the standard deviation is 1.20 cm. You need to specify the model, and the problem. Use <code><a href="https://rdrr.io/r/stats/Normal.html">?dnorm</a></code> or <code><a href="https://rdrr.io/r/stats/Normal.html">?pnorm</a></code> and look at your options (<a href="#fig-dpq_examp">Figure&nbsp;<span>3.2</span></a>).</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># cumulative probability: which bit of the curve does this relate to?</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span>q <span class="op">=</span> <span class="fl">38</span>, mean <span class="op">=</span> <span class="fl">37.6</span>, sd <span class="op">=</span> <span class="fl">1.2</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>Q78. Which area on <a href="#fig-normal_herring">Figure&nbsp;<span>3.1</span></a> are we interested in?</em></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-dpq_examp" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="P3_normal_files/figure-html/fig-dpq_examp-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption class="figure-caption">Figure&nbsp;3.2: Functions for distributions in R illustrated with a standard normal.</figcaption></figure>
</div>
</div>
</div>
<p>We can plot any normal distribution we like. Play with the values for <code>mu</code> and <code>sigma</code> below, adjusting the values for <code>from</code> and <code>to</code> as needed to see the distribution.</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mu</span> <span class="op">&lt;-</span> <span class="fl">37.6</span>  <span class="co"># population mean</span></span>
<span><span class="va">sigma</span> <span class="op">&lt;-</span> <span class="fl">1.2</span>  <span class="co"># population sd</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/curve.html">curve</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">dnorm</a></span><span class="op">(</span><span class="va">x</span>, mean <span class="op">=</span> <span class="va">mu</span>, sd <span class="op">=</span> <span class="va">sigma</span><span class="op">)</span>, from <span class="op">=</span> <span class="fl">30</span>, to <span class="op">=</span> <span class="fl">45</span>,</span>
<span>      main <span class="op">=</span> <span class="st">"Normal density"</span>, ylab <span class="op">=</span> <span class="st">"Density"</span>, xlab <span class="op">=</span> <span class="st">"Fish length, cm"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I can define a population like this <span class="math inline">\(y \sim Norm(37.6, 1.2)\)</span> and ask questions about <span class="math inline">\(P(y_i \leq a)\)</span>. E.g., what is the probability that a random fish drawn from this population is &lt;38 cm: <span class="math inline">\(P(y_i &lt; 38)\)</span>? The answer to that is 0.6306 or approximately 63%.</p>
<hr></section></section><section id="normal-model-adequacy" class="level2" data-number="3.2"><h2 data-number="3.2" class="anchored" data-anchor-id="normal-model-adequacy">
<span class="header-section-number">3.2</span> Normal model adequacy</h2>
<p>A separate fish population (long-eared wrasse) is described as <span class="math inline">\(y \sim Norm(5.14 cm, 25 cm)\)</span>.</p>
<p><em>Q81. What is the mean length and standard deviation of long-eared wrasse?</em></p>
<p><em>Q82. Calculate the proportion of fish that are expected to be less than zero cm in length.</em></p>
<p><em>Q84. What do your results indicate about the adequacy of the normal model to describe the length distribution of long-eared wrasse?</em></p>
<p><em>Q85. Recalculate your answers with 1/10<sup>th</sup> the standard deviation:</em> <span class="math inline">\(y \sim Norm(5.14, 2.5)\)</span><em>.</em></p>
<hr></section><section id="calculating-quantiles-in-the-normal-distribution" class="level2" data-number="3.3"><h2 data-number="3.3" class="anchored" data-anchor-id="calculating-quantiles-in-the-normal-distribution">
<span class="header-section-number">3.3</span> Calculating quantiles in the normal distribution</h2>
<p>A quantile is one of a series of values that divides a frequency distribution (i.e.&nbsp;a set of numbers) into equally represented groups (i.e., the same number of observations per group). For example, there are three values (Q1, Q2, Q3) that split a normal distribution into four groups (negative infinity to Q1, Q1 to Q2 (median), Q2 to Q3, and Q3 to positive infinity). Q3 - Q1 is the middle 50% of the data: the interquartile range.</p>
<p>There are 99 quantiles, called percentiles, that split your data into 100 groups. The 2.5 percentile is the value that splits your data into two groups corresponding to 2.5% along the distribution (from negative infinity for the normal distribution). Just as we can ask what proportion of a distribution is above or below a set value, we can also ask between what values will a given percentage of my data lie (e.g.&nbsp;what values correspond to the middle 95%?).</p>
<p>To solve this problem using R we use the quantile function <code><a href="https://rdrr.io/r/stats/Normal.html">qnorm()</a></code>, which uses the cumulative probability.</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">qnorm</a></span><span class="op">(</span>p <span class="op">=</span> <span class="fl">0.975</span>, mean <span class="op">=</span> <span class="fl">37.6</span>, sd <span class="op">=</span> <span class="fl">1.2</span><span class="op">)</span> <span class="co"># p is the cumulative probability </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 39.95196</code></pre>
</div>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">probs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span>from <span class="op">=</span> <span class="fl">0.1</span>, to <span class="op">=</span> <span class="fl">0.9</span>, by <span class="op">=</span> <span class="fl">0.2</span><span class="op">)</span> <span class="co"># vectorize for multiple values</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span><span class="va">probs</span>, quantiles<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">qnorm</a></span><span class="op">(</span>p <span class="op">=</span> <span class="va">probs</span>, mean <span class="op">=</span> <span class="fl">37.6</span>, sd <span class="op">=</span> <span class="fl">1.2</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              [,1]     [,2] [,3]     [,4]     [,5]
probs      0.10000  0.30000  0.5  0.70000  0.90000
quantiles 36.06214 36.97072 37.6 38.22928 39.13786</code></pre>
</div>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">probs_95</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.025</span>, <span class="fl">0.975</span><span class="op">)</span> <span class="co"># middle 95% (2.5% on either side)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">qnorm</a></span><span class="op">(</span>p <span class="op">=</span> <span class="va">probs_95</span>, mean <span class="op">=</span> <span class="fl">37.6</span>, sd <span class="op">=</span> <span class="fl">1.2</span><span class="op">)</span> <span class="co"># round as appropriate</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 35.24804 39.95196</code></pre>
</div>
</div>
<p>These values (<code>probs_95 = c(0.025, 0.975)</code>) identify proportions of the cumulative curve. That is, they identify the bottom 2.5% and the bottom 97.5% of the curve. Values between these two parameters constitute the central 95% of your data.</p>
<p>Let’s return to the herring data where the population was <span class="math inline">\(y \sim Norm(37.6, 1.2)\)</span>.</p>
<p><em>Q86. Find the values that capture the middle 95% and 90% of the herring data.</em></p>
<p>We quote our mean and interval like this: “The mean fish length and 95% interval was 37.6 cm (35.2 – 40.0 cm)”. Remember to use to same degree of precision (significant figures) for confidence intervals as was used to gather the data (or as specified in the question, defaulting to three).</p>
<p><em>Q87. What value would you expect to correspond to 0.5 (i.e., what value would be found half-way along your distribution)?</em></p>
<p><em>Q88. Check your answer above using <code><a href="https://rdrr.io/r/stats/Normal.html">qnorm()</a></code></em></p>
<p>To visualize regions of the normal distribution, let’s use <code>ggplot</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># The population: y ~ Norm(mean=37.6, sd=1.2) </span></span>
<span><span class="va">mu</span> <span class="op">&lt;-</span> <span class="fl">37.6</span></span>
<span><span class="va">sigma</span> <span class="op">&lt;-</span> <span class="fl">1.2</span></span>
<span><span class="co"># lower boundary and upper boundary of the region of interest</span></span>
<span><span class="va">lb</span> <span class="op">&lt;-</span> <span class="fl">36</span></span>
<span><span class="va">ub</span> <span class="op">&lt;-</span> <span class="fl">40</span> </span>
<span></span>
<span><span class="va">norm_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>z<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="op">-</span><span class="fl">4</span>, <span class="fl">4</span>, length.out<span class="op">=</span><span class="fl">100</span><span class="op">)</span>,</span>
<span>                  x<span class="op">=</span><span class="va">z</span><span class="op">*</span><span class="va">sigma</span> <span class="op">+</span> <span class="va">mu</span>,</span>
<span>                  densNorm<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">dnorm</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">mu</span>, <span class="va">sigma</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">norm_df</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">densNorm</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_ribbon.html">geom_ribbon</a></span><span class="op">(</span>data<span class="op">=</span><span class="va">norm_df</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">x</span> <span class="op">&gt;</span> <span class="va">lb</span> <span class="op">&amp;</span> <span class="va">x</span> <span class="op">&lt;</span> <span class="va">ub</span><span class="op">)</span>,</span>
<span>              <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>ymin<span class="op">=</span><span class="fl">0</span>, ymax<span class="op">=</span><span class="va">densNorm</span><span class="op">)</span>, fill<span class="op">=</span><span class="st">"steelblue"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x<span class="op">=</span><span class="st">"Herring length (cm)"</span>, </span>
<span>       y<span class="op">=</span><span class="st">"Probability density"</span>,</span>
<span>       subtitle<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"P("</span>, <span class="va">lb</span>, <span class="st">"&lt; y &lt;"</span>, <span class="va">ub</span>, <span class="st">") = "</span>, </span>
<span>                       <span class="fu"><a href="https://rdrr.io/r/base/Round.html">signif</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="va">ub</span>, <span class="va">mu</span>, <span class="va">sigma</span><span class="op">)</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="va">lb</span>, <span class="va">mu</span>, <span class="va">sigma</span><span class="op">)</span>, digits<span class="op">=</span><span class="fl">3</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span> <span class="co"># changes how the plot looks: ?theme</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-herring2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="P3_normal_files/figure-html/fig-herring2-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Figure&nbsp;3.3: The normal distribution illustrating probability of a random herring from your population having a length between 36 and 40 cm.</figcaption></figure>
</div>
</div>
</div>
<p><em>Q89. Change the parameters in the above to check that the values you generated for the 95% interval correspond when plugged into <code>lb</code> and <code>ub</code> in the code.</em></p>
<p><em>Q90. What is the difference between</em> <span class="math inline">\(&lt; x\)</span> <em>and</em> <span class="math inline">\(\leq x\)</span> <em>when applied to continuous data?</em></p>
<p><em>Q91. Does this also apply to discontinuous data?</em></p>
<p>Think about how intervals change when the population standard deviation changes.</p>
<p><em>Q92. With everything else equal, try doubling, quadrupling, and halving the standard deviation on the herring data then re-running the same code.</em></p>
<p><em>Q93. What effect does this have on your interval?</em></p>
<hr></section><section id="testing-for-normality" class="level2" data-number="3.4"><h2 data-number="3.4" class="anchored" data-anchor-id="testing-for-normality">
<span class="header-section-number">3.4</span> Testing for normality</h2>
<p>Many statistical tests assume that data are reasonably approximated by a normal distribution and have homogeneous variance. R can be used to formally test the assumption that data are normally distributed, though you should have some idea of whether this is likely through consideration of the data source. This applies particularly where you have a small sample size which makes evaluating the distribution challenging.</p>
<p>The data you collect will be part of a population. The normality check assesses the viability of the assumption that the data you collected were drawn from a population that was normally distributed. Note that populations are, in practice, <em>never</em> actually normally distributed. Your test is to assess how <em>reasonable</em> the assumption of normality is.</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">MS</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readxl.tidyverse.org/reference/read_excel.html">read_xlsx</a></span><span class="op">(</span><span class="st">"data/practical_3_4.xlsx"</span>, sheet <span class="op">=</span> <span class="st">"Mood shrimp"</span><span class="op">)</span></span>
<span><span class="co"># check the data using head(), str() etc.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqnorm</a></span><span class="op">(</span><span class="va">MS</span><span class="op">$</span><span class="va">Shrimp1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqline</a></span><span class="op">(</span><span class="va">MS</span><span class="op">$</span><span class="va">Shrimp1</span>, col <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="co"># the data fall near the line</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqnorm</a></span><span class="op">(</span><span class="va">MS</span><span class="op">$</span><span class="va">Shrimp2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqline</a></span><span class="op">(</span><span class="va">MS</span><span class="op">$</span><span class="va">Shrimp2</span>, col <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="co"># the data deviate widely from the line</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="P3_normal_files/figure-html/qq-examp-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Normal (QQ) plots. The left indicates that the normality assumption might be reasonable, not so on the right.</figcaption></figure>
</div>
</div>
</div>
<p>The axes on the probability plots have been rescaled so that, if your data are perfectly normal, the data points would fall on a straight line (the red line on the graphs generated by <code><a href="https://rdrr.io/r/stats/qqnorm.html">qqline()</a></code>). Any deviation from the red straight line in your data indicates a lack of normality. What we need to assess is how serious any deviation is and whether it is sufficient to indicate that the assumption of normality is not ‘reasonable’. This is a subjective decision, and two different statisticians may tell you different answers about the same data.</p>
<p>As your sample size decreases, it will be increasingly difficult to see if your data are reasonably approximated by a normal distribution. There are many formal statistical methods for assessing normality, but as we already know it is impossible for your data to have been drawn from a population that is normal and this means such tests are largely redundant. You must assess the assumptions of your model (e.g.&nbsp;the general linear model, which includes ANOVA and linear regression), but you should be aware that all data fails the assumptions. However, this doesn’t mean the outputs from such models aren’t useful - provided the assumptions are ‘reasonably’ well met. There is no hard rule as to what constitutes ‘reasonable’!</p>
<p><em>Q94. Make histograms of both <code>Shrimp1</code> and <code>Shrimp2</code>. Comment on their apparent distributions.</em></p>
<hr></section><section id="transformations" class="level2" data-number="3.5"><h2 data-number="3.5" class="anchored" data-anchor-id="transformations">
<span class="header-section-number">3.5</span> Data transformations</h2>
<p>The assumption that our sample data are drawn from a normally distributed population is central to the use of many important inferential statistical techniques. However, frequently it is <em>not</em> reasonable to assume that data are likely to be normally distributed and they ‘fail’ normality tests (e.g.&nbsp;clearly do not fall on the red <code><a href="https://rdrr.io/r/stats/qqnorm.html">qqline()</a></code>).</p>
<p>Non-normality often occurs because our measurements are near a logical zero. For example, chemical concentrations (e.g., of zinc in sediments) is limited by zero; you cannot have negative zinc concentrations. Similarly, you cannot have negative lengths, time, mass, proportions, etc. Where data is collected ‘near’ a logical zero they are often not normally distributed, since the normal distribution predicts a negative-value ‘tail’ which is impossible.</p>
<p>There are several simple mathematical transformation options that you can use in an attempt to convert your data to something that is reasonably approximated by a normal distribution even if it is not well approximated in the original measurement units.</p>
<p>Here we will consider four common transformations. These are the log (base 10 or natural), the square-root, the arcsine, and the logit transformation. Often transformations will also correct unequal variances (see <a href="P5_ANOVA_regression.html"><span>Chapter&nbsp;5</span></a>) in addition to non-normality so they are very useful. The appropriate transformation depends on the data.</p>
<ul>
<li>Log (<code><a href="https://rdrr.io/r/base/Log.html">log()</a></code>, inverse: <code><a href="https://rdrr.io/r/base/Log.html">exp()</a></code>): When the distribution is skewed right and all values are &gt;0. Often ‘cures’ heteroscedasticity.<br>
</li>
<li>Square-root (<code><a href="https://rdrr.io/r/base/MathFun.html">sqrt()</a></code>, inverse: <code>^2</code>): When the measurements are areas (e.g., leaf areas). Often used to ‘down-weight’ common species (e.g., <a href="P6_machine_learning.html"><span>Chapter&nbsp;6</span></a>), which is unrelated to model assumptions. Values must be &gt;0.<br>
</li>
<li>Arcsine (<code><a href="https://rdrr.io/r/base/Trig.html">asin()</a></code>, inverse: <code>sin()^2</code>): When the measurements are proportions. Tends to stretch out the tails (e.g., near 0 or 1 for proportions) and squash the middle (e.g., near 0.5).<br>
</li>
<li>Logit (<code><a href="https://rdrr.io/pkg/boot/man/logit.html">boot::logit()</a></code>, inverse: <code><a href="https://rdrr.io/pkg/boot/man/inv.logit.html">boot::inv.logit()</a></code>): Used for proportions excluding 0 and 1. Also commonly used in models with a binary response variable (e.g., survival probability predicted by temperature, where the response variable is ‘alive’/‘dead’).</li>
</ul>
<p>Identifying the correct transformation can be led by an underlying comprehension of the nature of the data. However, this often doesn’t work so expect some trial and error.</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">positive_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>orig<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0.01</span>, <span class="fl">10</span>, length.out<span class="op">=</span><span class="fl">1e3</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>sqrt<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">orig</span><span class="op">)</span>,</span>
<span>         ln<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">orig</span><span class="op">)</span>,</span>
<span>         inv.logit<span class="op">=</span><span class="fu">boot</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/boot/man/inv.logit.html">inv.logit</a></span><span class="op">(</span><span class="va">orig</span><span class="op">)</span>,</span>
<span>         squared<span class="op">=</span><span class="va">orig</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span><span class="op">(</span>cols<span class="op">=</span><span class="fl">2</span><span class="op">:</span><span class="fl">5</span>, names_to<span class="op">=</span><span class="st">"transformation"</span>, values_to<span class="op">=</span><span class="st">"new_value"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">positive_df</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">orig</span>, <span class="va">new_value</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="op">~</span><span class="va">transformation</span>, scales<span class="op">=</span><span class="st">"free"</span>, nrow<span class="op">=</span><span class="fl">1</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>main<span class="op">=</span><span class="st">"Positive values"</span>, x<span class="op">=</span><span class="st">"Original"</span>, y<span class="op">=</span><span class="st">"Transformed"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-trans_positiveData" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="P3_normal_files/figure-html/fig-trans_positiveData-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption class="figure-caption">Figure&nbsp;3.4: Effect of common transformations on positive data.</figcaption></figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">proportion_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>orig<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0.01</span>, <span class="fl">0.99</span>, length.out<span class="op">=</span><span class="fl">1e3</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>sqrt<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">orig</span><span class="op">)</span>,</span>
<span>         ln<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">orig</span><span class="op">)</span>,</span>
<span>         asin<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/Trig.html">asin</a></span><span class="op">(</span><span class="va">orig</span><span class="op">)</span>,</span>
<span>         logit<span class="op">=</span><span class="fu">boot</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/boot/man/logit.html">logit</a></span><span class="op">(</span><span class="va">orig</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span><span class="op">(</span>cols<span class="op">=</span><span class="fl">2</span><span class="op">:</span><span class="fl">5</span>, names_to<span class="op">=</span><span class="st">"transformation"</span>, values_to<span class="op">=</span><span class="st">"new_value"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">proportion_df</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">orig</span>, <span class="va">new_value</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="op">~</span><span class="va">transformation</span>, scales<span class="op">=</span><span class="st">"free"</span>, nrow<span class="op">=</span><span class="fl">1</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>main<span class="op">=</span><span class="st">"Proportions"</span>, x<span class="op">=</span><span class="st">"Original value"</span>, y<span class="op">=</span><span class="st">"Transformed value"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-trans_proportionalData" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="P3_normal_files/figure-html/fig-trans_proportionalData-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption class="figure-caption">Figure&nbsp;3.5: Effect of common transformations on proportions.</figcaption></figure>
</div>
</div>
</div>
<p><em>Q95. Using the Radon concentration worksheet in practical_3_4.xlsx, plot the data. Do they look normally distributed?</em></p>
<p><em>Q96. In your own time,use R to determine the log, square root, and reciprocals (and combinations of all of them: at least one converts the data to approximate normality).</em></p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># get the Radon data into R; the units are parts per billion</span></span>
<span><span class="fu">readxl</span><span class="fu">::</span><span class="fu"><a href="https://readxl.tidyverse.org/reference/excel_sheets.html">excel_sheets</a></span><span class="op">(</span><span class="st">"data/practical_3_4.xlsx"</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Cod lengths"           "Shrimps"               "Caffeine"             
 [4] "Non-parametric shrimp" "Mood shrimp"           "Mood shrimp2"         
 [7] "Swimming activity"     "Clare's Al data"       "Distribution"         
[10] "Radon (ppb)"           "Zinc conc"             "Heart-beat,2012"      
[13] "Sheet1"               </code></pre>
</div>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># load the dataset and try some transformations</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>Q97. Generate a vector of numbers and then use <code><a href="https://rdrr.io/r/base/MathFun.html">sqrt()</a></code> on them.</em></p>
<hr></section><section id="functions-in-r" class="level2" data-number="3.6"><h2 data-number="3.6" class="anchored" data-anchor-id="functions-in-r">
<span class="header-section-number">3.6</span> Functions in R</h2>
<p>Everything that <em>does</em> in R is a function. Writing your own functions becomes useful as you use R more and more often. It can keep your code legible and reduce work for yourself (since any changes need to be done in only one location instead of everywhere you’ve repeated the same code).</p>
<p>We’ll create a function called <code>trim_values()</code>, which takes a single argument (<code>x</code>), formats it to three digits, and returns the formatted output. Play around with the function to see how it works. We’ll use this function to ‘clean’ our output. In order to use the function, you must run the code defining it first. You will see your functions listed (alongside your dataframes, vectors, lists, etc) in RStudio’s ‘Environment’ pane.</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">trim_values</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/format.html">format</a></span><span class="op">(</span><span class="va">x</span>, digits <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span></span>
<span><span class="op">}</span> </span>
<span></span>
<span><span class="co"># After running the code above, we can use the function:</span></span>
<span><span class="fu">trim_values</span><span class="op">(</span><span class="fl">1.23456</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "1.23"</code></pre>
</div>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">long_numbers</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">2</span>, <span class="fl">1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>orig<span class="op">=</span><span class="va">long_numbers</span>,</span>
<span>           clean<span class="op">=</span><span class="fu">trim_values</span><span class="op">(</span><span class="va">long_numbers</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      orig clean
1 5.378487  5.38
2 3.906306  3.91
3 3.823875  3.82</code></pre>
</div>
</div>
<p>Notice anything strange about the output? The function <code><a href="https://rdrr.io/r/base/format.html">format()</a></code> converts the vector from <code>numeric</code> to <code>character</code> to display each value with the same number of characters. The <code>digits=3</code> argument is also taken as a suggestion (kind of like <code>breaks</code> in <code><a href="https://rdrr.io/r/graphics/hist.html">hist()</a></code>). Try some of the other options in <code><a href="https://rdrr.io/r/base/format.html">format()</a></code> or adjust the <code>digits</code> argument, re-running the function definition each time to see the changes.</p>
<hr></section><section id="the-central-limit-theorem" class="level2" data-number="3.7"><h2 data-number="3.7" class="anchored" data-anchor-id="the-central-limit-theorem">
<span class="header-section-number">3.7</span> The central limit theorem</h2>
<p>The central limit theorem (CLT) is about how <em>sample means</em> are distributed.</p>
<p>The CLT states that <strong>the means of normally distributed data will, themselves, be normally distributed</strong>. In addition, the theorem states that <strong>the means of data which are NOT normally distributed will be normally distributed if the sample size is sufficiently large</strong>. In this practical we are going to demonstrate this theorem using random data generated from various probability distributions.</p>
<section id="the-distribution-of-means-from-various-data-distributions" class="level3" data-number="3.7.1"><h3 data-number="3.7.1" class="anchored" data-anchor-id="the-distribution-of-means-from-various-data-distributions">
<span class="header-section-number">3.7.1</span> The distribution of means from various data distributions</h3>
<p>The following code generates a non-normally distributed dataset (<code>obs_data</code>), repeatedly takes samples from it (<code>num_samples</code> samples, with each sample made up of <code>sample_size</code> random observations from <code>obs_data</code>), and then plots histograms and QQ-plots for the raw data and for the sample means.</p>
<p>Copy the code and experiment with the <code>sample_size</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Run this code, then adjust the values for obs_data as you like.</span></span>
<span><span class="co"># Play with more distributions if you want: ?stats::distributions</span></span>
<span><span class="va">obs_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">2000</span>, <span class="fl">200</span>, <span class="fl">20</span><span class="op">)</span>, </span>
<span>              <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">1500</span>, <span class="fl">100</span>, <span class="fl">20</span><span class="op">)</span>, </span>
<span>              <span class="fu"><a href="https://rdrr.io/r/stats/Lognormal.html">rlnorm</a></span><span class="op">(</span><span class="fl">100</span>, <span class="fl">5</span>, <span class="fl">0.5</span><span class="op">)</span>,</span>
<span>              <span class="fu"><a href="https://rdrr.io/r/stats/Poisson.html">rpois</a></span><span class="op">(</span><span class="fl">1000</span>, <span class="fl">15</span><span class="op">)</span>, </span>
<span>              <span class="fu"><a href="https://rdrr.io/r/stats/Poisson.html">rpois</a></span><span class="op">(</span><span class="fl">500</span>, <span class="fl">30</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">xlims</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/range.html">range</a></span><span class="op">(</span><span class="va">obs_data</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Define size of each sample and the number of sampling repeats</span></span>
<span><span class="va">sample_size</span> <span class="op">&lt;-</span> <span class="fl">30</span></span>
<span><span class="va">num_samples</span> <span class="op">&lt;-</span> <span class="fl">10000</span></span>
<span></span>
<span><span class="co"># Sample num_samples times from obs_data, with n = sample_size for each sample</span></span>
<span><span class="va">sample_means</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">numeric</a></span><span class="op">(</span>length<span class="op">=</span><span class="va">num_samples</span><span class="op">)</span> <span class="co"># initialize an empty vector</span></span>
<span><span class="kw">for</span><span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="va">num_samples</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">sample_i</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="va">obs_data</span>, <span class="va">sample_size</span>, replace<span class="op">=</span><span class="cn">T</span><span class="op">)</span></span>
<span>  <span class="va">sample_means</span><span class="op">[</span><span class="va">i</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">sample_i</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="co"># plot observed distribution</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mar <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">2</span>, <span class="fl">2</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span> </span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/hist.html">hist</a></span><span class="op">(</span><span class="va">obs_data</span>,</span>
<span>     main <span class="op">=</span> <span class="st">"Raw data: obs_data"</span>,</span>
<span>     sub <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"mean: "</span>, <span class="fu">trim_values</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">obs_data</span><span class="op">)</span><span class="op">)</span>, </span>
<span>                  <span class="st">", sd: "</span>, <span class="fu">trim_values</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">obs_data</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>,</span>
<span>     breaks <span class="op">=</span> <span class="fl">30</span>, xlab <span class="op">=</span> <span class="st">"Observed length (cm)"</span>, xlim <span class="op">=</span> <span class="va">xlims</span></span>
<span><span class="op">)</span> </span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqnorm</a></span><span class="op">(</span><span class="va">obs_data</span>, main <span class="op">=</span> <span class="st">"Raw data QQ"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqline</a></span><span class="op">(</span><span class="va">obs_data</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># plot distribution of sample means</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/hist.html">hist</a></span><span class="op">(</span><span class="va">sample_means</span>,</span>
<span>     main <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"Sample means, N: "</span>, <span class="va">sample_size</span><span class="op">)</span>,</span>
<span>     sub <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"mean: "</span>, <span class="fu">trim_values</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">sample_means</span><span class="op">)</span><span class="op">)</span>, </span>
<span>                  <span class="st">", sd: "</span>, <span class="fu">trim_values</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">sample_means</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>,</span>
<span>     breaks <span class="op">=</span> <span class="fl">30</span>, xlab <span class="op">=</span> <span class="st">"Mean length (cm)"</span>, xlim <span class="op">=</span> <span class="va">xlims</span></span>
<span><span class="op">)</span> </span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqnorm</a></span><span class="op">(</span><span class="va">sample_means</span>, main<span class="op">=</span><span class="st">"Sample mean QQ"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqline</a></span><span class="op">(</span><span class="va">sample_means</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-clt_examp" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="P3_normal_files/figure-html/fig-clt_examp-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Figure&nbsp;3.6: The central limit theorem in action (when n&gt;30).</figcaption></figure>
</div>
</div>
</div>
<p><em>Q98. What do you notice about the location of the mean as a function of N?</em></p>
<p><em>Q99. What do you notice about the spread around the mean of sample means as a function of sample size – why did the pattern you have observed occur?</em></p>
<p>The CLT states that <code>sample_means</code> will be normally distributed if (a) the underlying data are normally distributed, OR (b) the <code>sample_size</code> is large enough. With R, we can see this in action.</p>
<p>Note also the relationship between the sample size and the range of values for the sample mean. How does the standard deviation of <code>sample_means</code> change with changes in <code>sample_size</code>?.</p>
<hr></section></section><section id="the-standard-error-of-the-mean" class="level2" data-number="3.8"><h2 data-number="3.8" class="anchored" data-anchor-id="the-standard-error-of-the-mean">
<span class="header-section-number">3.8</span> The standard error of the mean</h2>
<p>The standard error of the mean is the standard deviation of sample means, of a given sample size, taken from a population. It is the standard deviation of the distribution shown in the lower histogram in <a href="#fig-clt_examp">Figure&nbsp;<span>3.6</span></a> : <code>sd(sample_means)</code>. Usually we only have a single sample rather than 10,000 (=<code>num_samples</code>). In that case, we estimate it from single sample as <span class="math inline">\({SE}_{\bar{y}} = \frac{sd(y)}{\sqrt{n}}\)</span>, where <span class="math inline">\(y\)</span> is a vector of <span class="math inline">\(n\)</span> observations.</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Simulate a normally distributed population with mean mu and sd sigma</span></span>
<span><span class="va">mu</span> <span class="op">&lt;-</span> <span class="fl">10</span></span>
<span><span class="va">sigma</span> <span class="op">&lt;-</span> <span class="fl">2</span></span>
<span><span class="va">sim_obs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">10000</span>, <span class="va">mu</span>, <span class="va">sigma</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Draw samples</span></span>
<span><span class="va">sample_size</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">10</span>, <span class="fl">30</span>, <span class="fl">100</span><span class="op">)</span> <span class="co"># size of each sample</span></span>
<span><span class="va">num_samples</span> <span class="op">&lt;-</span> <span class="fl">1000</span> <span class="co"># number of samples (=repeats) for each sample size</span></span>
<span></span>
<span><span class="va">sample_mean_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>N<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="va">sample_size</span>, each <span class="op">=</span> <span class="va">num_samples</span><span class="op">)</span>,</span>
<span>                         id<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="va">num_samples</span>, times <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">sample_size</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>sample_mean<span class="op">=</span><span class="fl">0</span><span class="op">)</span></span>
<span></span>
<span><span class="kw">for</span><span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">sample_mean_df</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">sample_i</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="va">sim_obs</span>, <span class="va">sample_mean_df</span><span class="op">$</span><span class="va">N</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">)</span></span>
<span>  <span class="va">sample_mean_df</span><span class="op">$</span><span class="va">sample_mean</span><span class="op">[</span><span class="va">i</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">sample_i</span><span class="op">)</span></span>
<span><span class="op">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sample_mean_df</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>N<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">N</span>, levels<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span>, labels<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"n:"</span>, <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">sample_mean</span>, colour<span class="op">=</span><span class="va">N</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_vline</a></span><span class="op">(</span>xintercept<span class="op">=</span><span class="va">mu</span>, linetype<span class="op">=</span><span class="fl">3</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_density.html">geom_density</a></span><span class="op">(</span>linewidth<span class="op">=</span><span class="fl">0.9</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_viridis.html">scale_colour_viridis_d</a></span><span class="op">(</span><span class="st">"Size of each sample"</span>, option<span class="op">=</span><span class="st">"mako"</span>, end<span class="op">=</span><span class="fl">0.85</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"Means of"</span>, <span class="va">num_samples</span>, <span class="st">"simulated samples"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-SEM" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="P3_normal_files/figure-html/fig-SEM-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Figure&nbsp;3.7: Simulated sample means.</figcaption></figure>
</div>
</div>
</div>
<p><em>Q100. Calculate the theoretical standard error of the mean for each <code>sample_size</code> given <code>sigma</code> (i.e., from the equation) and compare this with the standard error from the simulated sample means in <code>sample_mean_df</code>.</em></p>
<p>Hint:</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sample_mean_df</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span><span class="op">)</span> <span class="co"># what goes here?</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And here’s a tidy solution:</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sample_mean_df</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>se_sim<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">sample_mean</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">ungroup</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>se_calc<span class="op">=</span><span class="va">sigma</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
      N se_sim se_calc
  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
1     2  1.43    1.41 
2    10  0.595   0.632
3    30  0.346   0.365
4   100  0.205   0.2  </code></pre>
</div>
</div>
<p><em>Q101. Given what you know about the CLT, how does this change with non-normally distributed data? Try changing <code><a href="https://rdrr.io/r/stats/Normal.html">rnorm()</a></code> to <code><a href="https://rdrr.io/r/stats/Poisson.html">rpois()</a></code></em></p>
<p><em>Q102. Change <code>sigma</code> and <code>sample_size</code> and check that the standard error estimates are in line with their true values (i.e.&nbsp;as determined by using the standard error formula).</em></p>
<hr></section><section id="normal-approximations-for-other-distributions" class="level2" data-number="3.9"><h2 data-number="3.9" class="anchored" data-anchor-id="normal-approximations-for-other-distributions">
<span class="header-section-number">3.9</span> Normal approximations for other distributions</h2>
<p>In earlier exercises you saw that the Poisson distribution could be used to approximate the binomial distribution. In a conceptually similar way, the normal distribution can be used to approximate the Poisson model.</p>
<section id="the-normal-approximation-of-the-poisson-distribution" class="level3" data-number="3.9.1"><h3 data-number="3.9.1" class="anchored" data-anchor-id="the-normal-approximation-of-the-poisson-distribution">
<span class="header-section-number">3.9.1</span> The Normal approximation of the Poisson distribution</h3>
<p>Recall that the Poisson model takes only one parameter, the mean, and that where a variable is Poisson distributed the variance equals the mean. So if we have a variable <span class="math inline">\(y \sim Pois(10)\)</span>, the mean (say density per quadrat) is 10 and so is the variance. We now have the two parameters that define the normal distribution (the mean and variance).</p>
<p><em>Q103. For</em> <span class="math inline">\(y \sim Pois(10)\)</span> <em>write the equivalent normal distribution in the usual notation</em> (<span class="math inline">\(y /sim Norm(...)\)</span>)<em>.</em></p>
<p>As a rough guideline, a normal approximation is reasonable if <span class="math inline">\(\lambda \geq 30\)</span>. So <span class="math inline">\(y \sim Pois(10)\)</span> should not be approximated by the normal distribution while <span class="math inline">\(y \sim Pois(30)\)</span> could be. However, it is generally preferable to use the natural distribution for your data (e.g., a Poisson distribution for counts). The normal distribution is beneficial in some cases, but this is increasingly less so with modern methods.</p>
<p><em>Q104. For a Poisson distribution</em> <span class="math inline">\(y \sim Pois(40)\)</span> <em>define the normal approximation in the usual way</em> (<span class="math inline">\(y /sim Norm(...)\)</span>)<em>.</em></p>
<p><em>Q105. Using R and referring to</em> <a href="P2_binomial_poisson.html"><span>Chapter&nbsp;2</span></a>, <em>calculate</em> <span class="math inline">\(P(y_i \leq 35)\)</span> <em>from</em> <span class="math inline">\(y \sim Pois(40)\)</span> <em>(Ans = 0.242)</em></p>
<p><em>Q106. Using R, calculate</em> <span class="math inline">\(P(y_i &lt; 35)\)</span> <em>from the above normal approximation of the Poisson distribution (Ans = 0.215).</em></p>
<p><em>Q107. What do you think of the normal approximation?</em></p>
<p><em>Q108. Evaluate</em> <span class="math inline">\(P(y_i&lt;3\ |\ \lambda=5)\)</span> <em>using the Poisson model and its normal approximation.</em></p>
</section><section id="the-normal-approximation-of-the-binomial-distribution" class="level3" data-number="3.9.2"><h3 data-number="3.9.2" class="anchored" data-anchor-id="the-normal-approximation-of-the-binomial-distribution">
<span class="header-section-number">3.9.2</span> The Normal approximation of the binomial distribution</h3>
<p>Whilst we accept the fundamental difference between continuous and discrete data, in making continuous-variable measurements we inevitably allocate each measurement to a single measurement category (we are limited by our ability to measure, eg. to the nearest millimeter if using a ruler). If we wish to treat a continuous variable as a continuous variable, the number of categories between the smallest and largest measurement should be a minimum of ~30 (the upper limit doesn’t matter so much but there is no need to &gt;300). For example, suppose we were measuring fish-lengths and the min was 20 cm and the max 40 cm. That means there are 20 x 1 cm measurement units between them. This falls under our 30 unit minimum – measuring to the nearest cm would not be adequate. There are, however, 40 x 0.5 cm units between them so we could measure to the nearest 0.5 cm (we would probably use 0.1 cm though). But, even if we measure to the correct degree of precision, we are still categorizing the lengths. For example, a fish of 20.5 cm actually means we think that fish was between 20.45 and 20.55 cm.</p>
<p>What is the point of this? Well, if you have a binomially distributed variable where <span class="math inline">\(n\)</span>, the number of trials, is sufficiently large (meaning the number of outcomes is large too) then the binomial distribution begins to look like the normal distribution, particularly where <span class="math inline">\(p\)</span> is somewhere near 0.5. The general guideline is that where the number of trials multiplied by the smaller of the probability of success (<span class="math inline">\(p\)</span>) or the probability of failure (<span class="math inline">\(q=1-p\)</span>) is greater than 5 then we can reasonably use the normal distribution to model the data (i.e.&nbsp;both <span class="math inline">\(n*p &gt; 5\)</span> and <span class="math inline">\(n*(1-p) &gt; 5\)</span>).</p>
<p>Turtles lay clutches of 40 eggs. We might be interested in predicting the number of male and female offspring. Assume the proportion that are male is 0.5. Our investigation stems from the observation that several clutches of eggs, on a particular island, contained only 10 males. We might wonder how unlikely this was by chance, assuming <span class="math inline">\(P(male)=0.5\)</span>.</p>
<p><em>Q109. Referring to <a href="P2_binomial_poisson.html"><span>Chapter&nbsp;2</span></a></em> <em>if necessary, use the binomial model, calculate how unusual (i.e.&nbsp;the probability) it is to get</em> <span class="math inline">\(\leq 10\)</span> <em>males.</em></p>
<p><em>Q110. Plot your probability (i.e.&nbsp;from 0 – 40 males) as a bar graph. Comment on its shape.</em></p>
<p>The variance of a binomially distributed variable is simply <span class="math inline">\(n*p*q\)</span>.</p>
<p><em>Q111. Calculate the mean and variance of this population.</em></p>
<p><em>Q112. Are</em> <span class="math inline">\(n*p\)</span> <em>and</em> <span class="math inline">\(n*(1-p)\)</span> <em>both &gt;5?</em></p>
<p><em>Q113. Given these two variables, specify the equivalent normal distribution.</em></p>
<p>We have the ‘real’ distribution <span class="math inline">\(y \sim Binom(40,0.5)\)</span> and its normal approximation. We ask what is <span class="math inline">\(P(y_i \leq 10)\)</span> given <span class="math inline">\(y \sim Binom(40, 0.5)\)</span> and given <span class="math inline">\(y \sim Norm(20, \sqrt{10})\)</span>.</p>
<p><em>Q114. Calculate the Z score for 10 males then find the probability of making this observation.</em></p>
<p><em>Q115. How do the values from the different models compare?</em></p>
<hr></section></section><section id="conclusions" class="level2" data-number="3.10"><h2 data-number="3.10" class="anchored" data-anchor-id="conclusions">
<span class="header-section-number">3.10</span> Conclusions</h2>
<p>The normal distribution is central to statistics. A huge variety of observations are reasonably approximated by the normal distribution (or can be made to be normally distributed through transformation).</p>
<p>The normal distribution can be used to assess the likelihood of a given observation, if we know the population mean and standard deviation from which it came. Furthermore, given our knowledge of the population parameter (mean and variance) we can determine values which define intervals on that population. Frequently scientists determine the values that bound 95% of their data.</p>
<p>The central limit theorem says that sample means taken from a normally distributed population will themselves be normally distributed and, in addition, means of sufficiently large samples will also be normally distributed even where the original data are not normally distributed (the sample size required depends on the extent of the skew in the original data).</p>
<p>The normal distribution is a good approximation of the Poisson distribution when lambda is large and the binomial model where the number of trials is large and the probability of success around 0.5 (i.e.&nbsp;the distribution of values is not too skewed).</p>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./P2_binomial_poisson.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Binomial and Poisson Distributions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./P4_t_CIs.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">T distribution and confidence intervals</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>