<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>H2 Data Science Practicals - 5&nbsp; ANOVA and regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./P6_machine_learning.html" rel="next">
<link href="./P4_t_CIs.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./P5_ANOVA_regression.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">ANOVA and regression</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">H2 Data Science Practicals</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P0_R_setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R setup</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P1_R_recap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">R recap</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P2_binomial_poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Binomial and Poisson Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P3_normal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Normal distribution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P4_t_CIs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">T distribution and confidence intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P5_ANOVA_regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">ANOVA and regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P6_machine_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Machine Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./P7_appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Appendix</span></span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#analysis-of-variance-anova" id="toc-analysis-of-variance-anova" class="nav-link active" data-scroll-target="#analysis-of-variance-anova"><span class="header-section-number">5.1</span> Analysis of variance (ANOVA)</a>
  <ul class="collapse">
<li><a href="#anova-in-r" id="toc-anova-in-r" class="nav-link" data-scroll-target="#anova-in-r"><span class="header-section-number">5.1.1</span> ANOVA in R</a></li>
  <li><a href="#one-way-anova" id="toc-one-way-anova" class="nav-link" data-scroll-target="#one-way-anova"><span class="header-section-number">5.1.2</span> One-way ANOVA</a></li>
  <li><a href="#two-way-anova" id="toc-two-way-anova" class="nav-link" data-scroll-target="#two-way-anova"><span class="header-section-number">5.1.3</span> Two-way ANOVA</a></li>
  </ul>
</li>
  <li>
<a href="#regression" id="toc-regression" class="nav-link" data-scroll-target="#regression"><span class="header-section-number">5.2</span> Regression</a>
  <ul class="collapse">
<li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview"><span class="header-section-number">5.2.1</span> Overview</a></li>
  <li><a href="#linear-regression-in-r" id="toc-linear-regression-in-r" class="nav-link" data-scroll-target="#linear-regression-in-r"><span class="header-section-number">5.2.2</span> Linear regression in R</a></li>
  <li><a href="#plotting-the-regression-line-and-confidence-intervals" id="toc-plotting-the-regression-line-and-confidence-intervals" class="nav-link" data-scroll-target="#plotting-the-regression-line-and-confidence-intervals"><span class="header-section-number">5.2.3</span> Plotting the regression line and confidence intervals</a></li>
  </ul>
</li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions"><span class="header-section-number">5.3</span> Conclusions</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-P5" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">ANOVA and regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p>General linear models are a key member of the generalized linear modelling family and they are among the most widely used and reported models in the marine science literature, particularly biology. This course focuses on two subsets of linear models: ANOVA and regression. ANOVA and regression are typically used for different data modelling scenarios: ANOVA when you’ve got a categorical predictor variable(s) and regression when your predictor is continuous.</p>
<section id="analysis-of-variance-anova" class="level2" data-number="5.1"><h2 data-number="5.1" class="anchored" data-anchor-id="analysis-of-variance-anova">
<span class="header-section-number">5.1</span> Analysis of variance (ANOVA)</h2>
<p>ANOVA is a widely used modelling approach that enables you to compare means and put confidence intervals on the differences between those means. For a predictor with only two categories, ANOVA is identical to the 2-sample t-test, so we’ll just use ANOVA.</p>
<p>When you see “analysis of variance”, think “analysis of means”. In an ANOVA, we analyse the variance in the data in order to compare the means of different groups. In an ANOVA, we compare means by determining the ratio of “the variance between treatments and the overall mean” (large black arrows in <a href="#fig-var_sources">Figure&nbsp;<span>5.1</span></a>) and “the variance within treatments” (sum of the dotted arrows in <a href="#fig-var_sources">Figure&nbsp;<span>5.1</span></a>). The black line under the red dots in <a href="#fig-var_sources">Figure&nbsp;<span>5.1</span></a> shows the actual data distribution and the actual parameters for mean values (50 and 150 cm for A and B respectively). You then take samples from A and B (n=4 in this example) and, from these, derive your parameter estimates for the mean of each group and the overall mean.</p>
<p>In <a href="#fig-var_sources">Figure&nbsp;<span>5.1</span></a> below you can see that the solid black arrows are much larger than the dotted ones leading you to think that the chance that these two samples are drawn from the same population (with a value of the overall mean) as very unlikely. Make sure you understand <a href="#fig-var_sources">Figure&nbsp;<span>5.1</span></a> (more detail in the ANOVA lecture).</p>
<p>In most circumstances you know that the means that you are comparing with ANOVA are different (i.e.&nbsp;that testing a null hypothesis of no difference isn’t useful). ANOVA allows you to put confidence intervals around differences between means, or groups of means.</p>
<div id="fig-var_sources" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="figs/ANOVA_sources_of_var.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;5.1: Sources of variation (within group and between groups) as quantified by ANOVA.</figcaption></figure>
</div>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://readxl.tidyverse.org">readxl</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="anova-in-r" class="level3" data-number="5.1.1"><h3 data-number="5.1.1" class="anchored" data-anchor-id="anova-in-r">
<span class="header-section-number">5.1.1</span> ANOVA in R</h3>
<p>There are numerous variations on the theme of ANOVA. We cover one-way ANOVA and we mention two-way ANOVA with and without replication. The objective of ANOVA is to establish the size of the difference (called the ‘effect size’) between different groups (e.g., treatments or locations) and put a confidence interval on those differences.</p>
</section><section id="one-way-anova" class="level3" data-number="5.1.2"><h3 data-number="5.1.2" class="anchored" data-anchor-id="one-way-anova">
<span class="header-section-number">5.1.2</span> One-way ANOVA</h3>
<p>One-way ANOVA is a procedure we use to estimate the magnitude of differences between means of <span class="math inline">\(\geq\)</span> 2 groups. We also use it to put confidence intervals on those differences.</p>
<p>The first example data is the yield in <span class="math inline">\(\mu g\)</span> C <span class="math inline">\(ml^{-1}\)</span> of a species of microalgae (<em>Isochrysis galbana</em>) in laboratory culture exposed to three light levels (low, medium and high). We are interested in these particular light levels because they represent the means of winter, spring, and summer Scottish sun intensity. The data are in worksheet ‘Microalgae’.</p>
<p>Note: the function to conduct an ANOVA is <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code>. The function <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> converts various statistical model outputs to the standard ANOVA-table output (including any from the GLM family).</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">algae_wide_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readxl.tidyverse.org/reference/read_excel.html">read_excel</a></span><span class="op">(</span><span class="st">"data/practical_5.xlsx"</span>, sheet <span class="op">=</span> <span class="st">"Microalgae"</span><span class="op">)</span></span>
<span><span class="co"># check these data as usual</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>Q158. What is your objective in this type of experiment? What are you interested in estimating?</em></p>
<p><em>Q159. What assumptions should be met prior to undertaking parametric ANOVA?</em></p>
<p><em>Q160. Under which circumstances could you begin to relax the assumption that the data are normally distributed (think central limit theorem)?</em></p>
<p><em>Q161. Given your sample size can we assume normality of means?</em></p>
<p><em>Q162. Are the data normally distributed (be careful how you word your answer to this question, see the following question)?</em></p>
<p><em>Q163. Is it reasonable to assume that these data are drawn from a population that is normally distributed?</em></p>
<p>To work with our data, we need to rearrange the data so that the data is in a tidy format with each variable corresponding to one column, and each observation corresponding to one row. We’ll use the <em>tidyverse</em> as before.</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">algae_wide_df</span>, <span class="fl">2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
    low medium  high
  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
1  13.1   12    14.2
2  11.5   11.5  13.1</code></pre>
</div>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">algae_df</span> <span class="op">&lt;-</span> <span class="va">algae_wide_df</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span><span class="op">(</span><span class="fu"><a href="https://tidyselect.r-lib.org/reference/everything.html">everything</a></span><span class="op">(</span><span class="op">)</span>, names_to <span class="op">=</span> <span class="st">"Treatment"</span>, values_to <span class="op">=</span> <span class="st">"Yield"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">algae_df</span>, width<span class="op">=</span><span class="fl">80</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 15
Columns: 2
$ Treatment &lt;chr&gt; "low", "medium", "high", "low", "medium", "high", "low", "me…
$ Yield     &lt;dbl&gt; 13.07599, 12.00000, 14.20000, 11.53923, 11.50000, 13.10000, …</code></pre>
</div>
</div>
<p>While there are formal tests to evaluate model assumptions (e.g., the Shapiro-Wilkes test or the Bartlett test), a better way of checking model assumptions is to check residual patterns. A ‘residual’ is the difference between an actual data value and that predicted by the model. Here we have randomly assigned five cultures each of the same species to three specific treatments (light levels).</p>
<p><em>Q165. What type of experiment is this? (How many factors (=predictors)? Are they fixed or random?)</em></p>
<p>Next to conduct the analysis:</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">algae_aov</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">Yield</span> <span class="op">~</span> <span class="va">Treatment</span>, data <span class="op">=</span> <span class="va">algae_df</span><span class="op">)</span> <span class="co"># ?aov</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Before we look at the output, let’s assess the assumptions using the residuals. The default residual plots created by R are shown in <a href="#fig-algae_aov">Figure&nbsp;<span>5.2</span></a> and enables us to rapidly assess whether the model assumptions are reasonable.</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">2</span><span class="op">)</span>, mar<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>,<span class="fl">4</span>,<span class="fl">1</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span> </span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">algae_aov</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-algae_aov" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="P5_ANOVA_regression_files/figure-html/fig-algae_aov-1.png" class="img-fluid figure-img" width="528"></p>
<figcaption class="figure-caption">Figure&nbsp;5.2: Residual plots from one-way ANOVA.</figcaption></figure>
</div>
</div>
</div>
<p><strong>Interpretation of residual patterns:</strong></p>
<ul>
<li>
<strong>Upper left:</strong> Residuals v. fitted. This is the residual values against the fitted values. The fitted values are the means of the three groups (remember that ANOVA is about comparing means). The spread for the lower values (low and medium light) is higher than for the high light so this might make us consider the homoscedasticity assumption.<br>
</li>
<li>
<strong>Upper right:</strong> Normal Q-Q plot. This assesses the normality assumption. The points (each point is an observation) lie around the straight line so this assumption is reasonable. Note that general linear models assume that the means of groups are normally distributed, and this always applies when the means are based on large sample sizes (roughly <span class="math inline">\(n &gt; 30\)</span>). When <span class="math inline">\(n &lt; 30\)</span>, you should check that the distribution of the residuals is reasonably ‘normal’.<br>
</li>
<li>
<strong>Lower left:</strong> Scale-location. This specifically looks to assess whether residuals increase with fitted values, which is a common issue in these types of analysis. In this case, the scale decreases with fitted value. This is similar to the Upper Left plot, but with <code>sqrt(abs(standardized_residuals))</code> on the y-axis instead of just <code>residuals</code> to focus just on the magnitude of the residuals.<br>
</li>
<li>
<strong>Lower right:</strong> Constant leverage, residuals vs.&nbsp;factor levels. This indicates how each treatment is fitted (i.e.&nbsp;the residuals associated with each treatment). You might be concerned if one particular treatment was associated with extremely high residuals (outliers). R automatically identifies potential outliers (8, 11, and 13 in this case) for you to further assess. In this case there is nothing in particular to worry about.</li>
</ul>
<p>The residual plots allow you to investigate different aspects of the data and the how their assumptions are met. The interpretation of the plots overlaps in the sense that the same issue might be apparent in several of the plots.</p>
<p><em>Q166. What are the ‘fitted values’ for an ANOVA?</em></p>
<p><em>Q167. Are your effects fixed or random?</em></p>
<p><em>Q168. Assuming you have chosen</em> <span class="math inline">\(\alpha = 0.05\)</span><em>, what might you be interested in going on to test next? Hint: you are testing to see whether the means of three populations are different.</em></p>
<p>Everything looks OK, so we can then look at the results of the ANOVA.</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># anova(algae_aov) # outputs an anova-type table, but unnecessary with aov()</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">algae_aov</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)  
Treatment    2 10.050   5.025   6.487 0.0123 *
Residuals   12  9.296   0.775                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Reporting that there are ‘significant’ differences between means is not enough. What your readers should be interested in is what the differences between the means actually are, and how confident you are in your assessment. This can be provided by the Tukey test in R.</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">algae_grp_diffs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/TukeyHSD.html">TukeyHSD</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">algae_aov</span>, conf.level <span class="op">=</span> <span class="fl">0.95</span><span class="op">)</span> </span>
<span><span class="co"># HSD stands for 'honestly significant difference'</span></span>
<span><span class="va">algae_grp_diffs</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Yield ~ Treatment, data = algae_df)

$Treatment
                   diff       lwr        upr     p adj
low-high    -1.68922461 -3.174304 -0.2041449 0.0260570
medium-high -1.78000000 -3.265080 -0.2949203 0.0194474
medium-low  -0.09077539 -1.575855  1.3943043 0.9854641</code></pre>
</div>
</div>
<p>You can see that the mean yield at the high light level is higher than at both the low and medium: the 95% confidence interval of the difference in comparing high and low light levels are 1.69 (0.205, 3.17) <span class="math inline">\(\mu g\)</span> C <span class="math inline">\(ml^{-1}\)</span>. (I’ve inverted the results so the the difference is seen as positive (high - low rather than low - high)). This confidence interval is much more important than any P-values and you should report both (CI because it is useful, P value by convention).</p>
</section><section id="two-way-anova" class="level3" data-number="5.1.3"><h3 data-number="5.1.3" class="anchored" data-anchor-id="two-way-anova">
<span class="header-section-number">5.1.3</span> Two-way ANOVA</h3>
<p>You’ve had a look at one-way ANOVA (i.e., one predictor), which is a good starting point. However, in nature you often find numerous factors combine to influence an outcome. This is called an ‘interaction’. Two-way ANOVA allows you to investigate the nature of this interaction term. You can also get three-way ANOVA and more, but these get logistically challenging because you need to replicate across each level. The interpretation also gets increasingly difficult. You need to be aware of the existence of two-way ANOVA and what it offers, and how to interpret simple graphics (below), but we do not cover implementation of two-way ANOVA.</p>
<div id="fig-interactions" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="figs/interactions.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;5.3: Graphic illustrating differing levels of interaction on the response from two treatments A and B.</figcaption></figure>
</div>
<p>In <a href="#fig-interactions">Figure&nbsp;<span>5.3</span></a> we have the outcome of an experiment. Each dot on the plot represents the mean Response (e.g.&nbsp;growth) of a number of replicates, subject to the combination of Temperature (cold and hot) and Nutrient (N and P). We are interested in the main effects (Temp and Nutrient) and their interaction (Temp * Nutrient) In panel A, there is no effect of Temp on the Response (the lines between Cold and Hot are horizontal), but there is a main effect of Nutrient (P is higher than N). In B, there is an effect of Temp (Hot is, on average higher than Cold) but there is also an interaction as the effect of Hot is more for P than for N (where it has no effect in this example). In C, the interaction is stronger compared with B. In D, there are no treatment main effects because mean Cold = mean Hot and mean N = mean P, but there is a very strong interaction effect; the effect of Temp is reversed by Nutrient, so that the level of Nutrient (N or P) determines the effect of Temp. When it is Cold the Response is high for Nutrient P and low for Nutrient N, when it is Hot, the Response is low for Nutrient P and high for Nutrient N (but the average for hot=cold, and average for N=P)</p>
<hr></section></section><section id="regression" class="level2" data-number="5.2"><h2 data-number="5.2" class="anchored" data-anchor-id="regression">
<span class="header-section-number">5.2</span> Regression</h2>
<p>Correlation and regression are used to examine the strength of association between two variables. In correlation, both variables are measured (and therefore associated with measurement error). In regression, one variable is fixed (by the experimenter) and is assumed to have no ‘error’ associated with it and the other, called the ‘response variable’, is measured (so has measurement error). You must be able to distinguish which of correlation or regression analyses are most appropriate.</p>
<p>Correlation analysis is used to measure association, where you are not attempting to formally link cause-and-effect. Regression analysis is generally used where you have experimentally manipulated the fixed factor and are looking at the response in another factor. Causation is implicit in inferential regression analysis (correlation analysis is often used in ‘exploratory’ data analysis where any link between cause-and-effect is inherently more speculative).</p>
<p>The media often misreport science because it is difficult to resist the impulse to attribute causation. An overwhelming number of spurious correlations (i.e., those <em>clearly</em> having no causal relationship) are documented on <a href="https://tylervigen.com/spurious-correlations">tylervigen.com</a>.</p>
<section id="overview" class="level3" data-number="5.2.1"><h3 data-number="5.2.1" class="anchored" data-anchor-id="overview">
<span class="header-section-number">5.2.1</span> Overview</h3>
<p>Regression is at the heart of linear models. ANOVA and t-tests are, basically, special cases of linear regression models. The regression coefficient is a measure of the strength of the relationship between the dependent variable (the one you measure) and the independent variable (the one you fix like a fixed factor in ANOVA). The regression coefficient is denoted by <span class="math inline">\(R^2\)</span> compared with <span class="math inline">\(r\)</span> in correlation. The regression coefficient <span class="math inline">\(R^2\)</span> ranges from 0 to 1 (unlike <span class="math inline">\(r\)</span> which ranges from -1 to 1). A value <span class="math inline">\(R^2 = 0\)</span> indicates no relationship to the independent variable while <span class="math inline">\(R^2=1\)</span> indicates that the independent variable is entirely responsible for the variability in the measured variable.</p>
<p>As usual, null hypothesis significance testing is often applied to regression statistics. As usual, the null hypothesis being tested is usually “there is no functional relationship between the response and the predictor” and this is usually conceptually nonsense. In conducting regression analysis, your objective is to quantify to the most appropriate precision and accuracy possible the relationship between X (the aspect you control, the predictor, plotted on the X axis) and Y (the variable you measure, the response, plotted on the Y axis). Your objective is to quantify this relationship, put confidence intervals on it, and then interpret your findings in relation to the objectives of the study and in relation to other research.</p>
<p><em>Q169. What does the plot look like when there is no relationship between the predictor and the response?</em></p>
<p>Let us now consider an example in which cause and effect does exist. The data in worksheet ‘Beetles’ in <em>practical_6.xlsx</em> shows the weight loss in <em>Tribolium confusum</em>, the confused flour beetle, at different relative humidities (data from Sokal and Rohlf, 1995). The relative humidity (RH) to which the beetles are exposed can be fixed and the weight loss (via evaporative losses) of the beetles then assessed. There is no way that the null hypothesis can be true in this case: humidity will obviously influence weight loss in beetles.</p>
<p><em>Q170. In this case, what is your response variable (what are you measuring) and your predictor (i.e.&nbsp;what is it that you are manipulating to determine the extent of the response)?</em></p>
<p><em>Q171. Plot the data in R and check your prediction. In this case, the predictor must be displayed on the x-axis and the response must be on the y-axis.</em></p>
<p>We are interested in whether the whole data set can be usefully represented by a linear regression relationship. We wish to estimate the relationship, and put a confidence interval on our estimate. Common sense tells us that there <em>is</em> some sort of relationship (testing a null hypothesis is not very useful) but it might go in either direction (positive or negative) and we don’t know the strength (i.e.&nbsp;slope) of that relationship.</p>
</section><section id="linear-regression-in-r" class="level3" data-number="5.2.2"><h3 data-number="5.2.2" class="anchored" data-anchor-id="linear-regression-in-r">
<span class="header-section-number">5.2.2</span> Linear regression in R</h3>
<p>In R we can use a variety of techniques to conduct linear regression. The easiest is to use <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>. It is worth noting that <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> would also work for all your other general linear models (e.g.&nbsp;ANOVA). They are, in fact, the same model, it is just the default output (and necessary input formatting) that differs. Try reproducing the ANOVAs above with <code>anova(lm(...))</code>.</p>
<p>Import data and begin:</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">beetle_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readxl.tidyverse.org/reference/read_excel.html">read_excel</a></span><span class="op">(</span><span class="st">"data/practical_6.xlsx"</span>, sheet <span class="op">=</span> <span class="st">"Beetles"</span><span class="op">)</span></span>
<span><span class="co"># inspect the dataframe, then make a scatter plot</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">WeightLoss_Mg</span> <span class="op">~</span> <span class="va">Humidity</span>, data <span class="op">=</span> <span class="va">beetle_df</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-beetle_scatter" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="P5_ANOVA_regression_files/figure-html/fig-beetle_scatter-1.png" class="img-fluid figure-img" width="384"></p>
<figcaption class="figure-caption">Figure&nbsp;5.4: Beetle weight loss as a function of relative humidity.</figcaption></figure>
</div>
</div>
</div>
<p>An aside on plotting: you can provide <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code> with either a vector for the x-axis and a vector for the y-axis (i.e., <code>plot(x_var, y_var)</code>) <em>or</em> you can use a formula, specifying the dataframe (i.e., <code>plot(y ~ x, data=data_df)</code>). Just be aware of which variable is on which axis.</p>
<p>Now we have explored and plotted the data we can conduct the regression analysis.</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># weight loss is modelled as (~) a function of humidity</span></span>
<span><span class="va">beetle_lm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">WeightLoss_Mg</span> <span class="op">~</span> <span class="va">Humidity</span>, data <span class="op">=</span> <span class="va">beetle_df</span><span class="op">)</span> </span>
<span><span class="co"># beetle_lm</span></span>
<span><span class="co"># str(beetle_lm) # lm outputs are complex structures</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Before we go on and interpret the model output we need to assess the model assumptions. This is done in the same way as for ANOVA with the same commands.</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">2</span><span class="op">)</span>, mar<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>,<span class="fl">4</span>,<span class="fl">1</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="co"># set up 4 in 1 plot.</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">beetle_lm</span><span class="op">)</span> <span class="co"># plot the regression residuals.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-beetle_diag" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="P5_ANOVA_regression_files/figure-html/fig-beetle_diag-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption class="figure-caption">Figure&nbsp;5.5: Regression diagnostics</figcaption></figure>
</div>
</div>
</div>
<p>The small sample size here (<span class="math inline">\(n=9\)</span>) makes a proper analysis of the residuals difficult. The plot should be assessed in the same way as for the ANOVA residuals. Basically, any pattern is bad. The upper left (Residuals v Fitted) doesn’t cause any major concern, though the upper right (Normal QQ) indicates a possible problem. Scale-Location (lower left) is difficult to interpret but no obvious pattern is present. The Residuals v. leverage (lower right) indicates a potential issue as well. A point with a large residual (i.e.&nbsp;where it is very different to that expected by the model) and with a high leverage (i.e.&nbsp;at the extreme ends of the predictors range) has a large Cook’s distance and has a disproportionate effect on the slope and intercept. These points should be examined in more detail.</p>
<p><em>Q172. Which point has the largest Cook’s distance?</em></p>
<p>We will now proceed to looking at the linear regression analysis results on the basis that the residuals do not raise any concerns.</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">beetle_lm</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = WeightLoss_Mg ~ Humidity, data = beetle_df)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.46397 -0.03437  0.01675  0.07464  0.45236 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  8.704027   0.191565   45.44 6.54e-10 ***
Humidity    -0.053222   0.003256  -16.35 7.82e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2967 on 7 degrees of freedom
Multiple R-squared:  0.9745,    Adjusted R-squared:  0.9708 
F-statistic: 267.2 on 1 and 7 DF,  p-value: 7.816e-07</code></pre>
</div>
</div>
<p>The regression equation of the form <span class="math inline">\(y = a + bx\)</span> can be determined. The regression equation is:</p>
<p><span class="math inline">\(WeightLoss = 8.70 - 0.05322 * humidity\)</span></p>
<p>Common-sense check: the coefficient is negative. As the humidity increases, the weight loss decreases (as expected and shown in the scatter plot).</p>
<p><em>Q173. What is the effect on weight loss of increasing the relative humidity by 10%?</em></p>
<p><em>Q174. What is the weight loss, predicted by the model, when relative humidity is 0%?</em></p>
<p><em>Q175. What does the model suggest the weight loss will be when relative humidity is -50% and +150%? Are these values sensible? What does this tell you about extrapolating beyond the data range in using regression analysis in predictions?</em></p>
<p>The residual error is the variance in y around the line. The <span class="math inline">\(R^2\)</span> is the proportion of this variance that is explained by the regression line. In the current case <span class="math inline">\(R^2 = 0.97\)</span>. This is an extremely high value and indicates that the regression model is extraordinarily good at accounting for the variance in weight loss based on the relative humidity.</p>
<p>The P values allow us to assess if the slope and the intercept are likely different from zero.</p>
<p><em>Q176. Given the very high</em> <span class="math inline">\(R^2\)</span> <em>(and looking at your plot) would you expect the regression model to be significantly better than the null model in explaining the variance in weight loss?</em></p>
<p><em>Q177. With</em> <span class="math inline">\(\alpha = 0.05\)</span><em>, do you reject or accept the null hypothesis? What would you wish to report in relation to the slope coefficient if you were reporting the results from this analysis?</em></p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">beetle_lm</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %      97.5 %
(Intercept)  8.25104923  9.15700538
Humidity    -0.06092143 -0.04552287</code></pre>
</div>
</div>
<p>The confidence intervals are, again, ‘clunky’ to describe.</p>
<p>If we imagine there were many alternate you’s (like in a multiverse) repeating the same experiment on the same population with the same sample size (but independent <em>samples</em>), and each ‘you’ calculated 95% CIs with <code><a href="https://rdrr.io/r/stats/confint.html">confint()</a></code>, then 95% of you would have intervals that include the true population intercept and slope. While you do not know if you are in the unlucky 5% that failed to capture the population values, the 95% confidence interval serves as our best estimate for likely values (but see Bayesian statistics for more intuitive intervals!).</p>
</section><section id="plotting-the-regression-line-and-confidence-intervals" class="level3" data-number="5.2.3"><h3 data-number="5.2.3" class="anchored" data-anchor-id="plotting-the-regression-line-and-confidence-intervals">
<span class="header-section-number">5.2.3</span> Plotting the regression line and confidence intervals</h3>
<p>A regression model (i.e.&nbsp;the linear relationship between the predictor and response variables) allows us to predict values for any value of the predictor, along with confidence levels. We can plot this regression line without too much effort.</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">beetle_pred_line</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">beetle_lm</span>, interval <span class="op">=</span> <span class="st">"confidence"</span>, level <span class="op">=</span> <span class="fl">0.95</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">WeightLoss_Mg</span> <span class="op">~</span> <span class="va">Humidity</span>, data <span class="op">=</span> <span class="va">beetle_df</span>, ylim<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">10</span><span class="op">)</span>,</span>
<span>     xlab <span class="op">=</span> <span class="st">"Relative humidity (%)"</span>, ylab <span class="op">=</span> <span class="st">"Weight loss (mg)"</span><span class="op">)</span> </span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span><span class="va">beetle_df</span><span class="op">$</span><span class="va">Humidity</span>, <span class="va">beetle_pred_line</span><span class="op">[</span>, <span class="st">"fit"</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span><span class="va">beetle_df</span><span class="op">$</span><span class="va">Humidity</span>, <span class="va">beetle_pred_line</span><span class="op">[</span>, <span class="st">"lwr"</span><span class="op">]</span>, lty <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span><span class="va">beetle_df</span><span class="op">$</span><span class="va">Humidity</span>, <span class="va">beetle_pred_line</span><span class="op">[</span>, <span class="st">"upr"</span><span class="op">]</span>, lty <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-beetle_regline" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="P5_ANOVA_regression_files/figure-html/fig-beetle_regline-1.png" class="img-fluid figure-img" width="384"></p>
<figcaption class="figure-caption">Figure&nbsp;5.6: Regression line (solid) with upper and lower 95% confidence intervals on the regression line (dashed).</figcaption></figure>
</div>
</div>
</div>
<p>Try generating 90% confidence intervals and add them to the plot.</p>
<p><em>Q178. Which will have the wider interval, a 99.99% interval or a 50% interval and why?</em></p>
<p><em>Q179. Do the confidence intervals in <a href="#fig-beetle_regline">Figure&nbsp;<span>5.6</span></a> run parallel to the regression line?</em></p>
<p><em>Q180. If not, what does this suggest about the degree of confidence you have in values predicted at various points along the line?</em></p>
<p><em>Q181. At what value of relative humidity are your predictions of weight loss likely most accurate?</em></p>
<p>We can make predictions based on our regression line, and put confidence intervals on those predictions. Say we had a relative humidity of 50% in the above example. You could ask for the model-predicted weight loss and you’d want confidence intervals on that prediction.</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># predict() needs a data.frame with the same predictors used in beetle_lm</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">beetle_lm</span>, </span>
<span>        newdata <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>Humidity <span class="op">=</span> <span class="fl">50</span><span class="op">)</span>, </span>
<span>        interval <span class="op">=</span> <span class="st">"predict"</span>, </span>
<span>        level <span class="op">=</span> <span class="fl">0.95</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      fit      lwr      upr
1 6.04292 5.303471 6.782368</code></pre>
</div>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># or more fully:</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">beetle_lm</span>, </span>
<span>        newdata <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>Humidity <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">100</span>, by<span class="op">=</span><span class="fl">25</span><span class="op">)</span><span class="op">)</span>, </span>
<span>        interval <span class="op">=</span> <span class="st">"predict"</span>, </span>
<span>        level <span class="op">=</span> <span class="fl">0.95</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 8.704027 7.868990 9.539064
2 7.373474 6.608630 8.138317
3 6.042920 5.303471 6.782368
4 4.712366 3.949031 5.475701
5 3.381812 2.549540 4.214084</code></pre>
</div>
</div>
<p>And we can plot these intervals too:</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">new_humidity_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>Humidity <span class="op">=</span> <span class="fl">0</span><span class="op">:</span><span class="fl">100</span><span class="op">)</span></span>
<span><span class="va">beetle_pred_line</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">beetle_lm</span>, </span>
<span>                            newdata <span class="op">=</span> <span class="va">new_humidity_df</span>,</span>
<span>                            interval <span class="op">=</span> <span class="st">"confidence"</span>, </span>
<span>                            level <span class="op">=</span> <span class="fl">0.95</span><span class="op">)</span></span>
<span><span class="va">beetle_pred_obs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">beetle_lm</span>,</span>
<span>                           newdata <span class="op">=</span> <span class="va">new_humidity_df</span>, </span>
<span>                           interval <span class="op">=</span> <span class="st">"prediction"</span>, </span>
<span>                           level <span class="op">=</span> <span class="fl">0.95</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">WeightLoss_Mg</span> <span class="op">~</span> <span class="va">Humidity</span>, data <span class="op">=</span> <span class="va">beetle_df</span>, ylim<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">10</span><span class="op">)</span>,</span>
<span>     xlab <span class="op">=</span> <span class="st">"Relative humidity (%)"</span>, ylab <span class="op">=</span> <span class="st">"Weight loss (mg)"</span><span class="op">)</span> </span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span><span class="va">new_humidity_df</span><span class="op">$</span><span class="va">Humidity</span>, <span class="va">beetle_pred_line</span><span class="op">[</span>, <span class="st">"fit"</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span><span class="va">new_humidity_df</span><span class="op">$</span><span class="va">Humidity</span>, <span class="va">beetle_pred_line</span><span class="op">[</span>, <span class="st">"lwr"</span><span class="op">]</span>, lty <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span><span class="va">new_humidity_df</span><span class="op">$</span><span class="va">Humidity</span>, <span class="va">beetle_pred_line</span><span class="op">[</span>, <span class="st">"upr"</span><span class="op">]</span>, lty <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span><span class="va">new_humidity_df</span><span class="op">$</span><span class="va">Humidity</span>, <span class="va">beetle_pred_obs</span><span class="op">[</span>, <span class="st">"lwr"</span><span class="op">]</span>, lty <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span><span class="va">new_humidity_df</span><span class="op">$</span><span class="va">Humidity</span>, <span class="va">beetle_pred_obs</span><span class="op">[</span>, <span class="st">"upr"</span><span class="op">]</span>, lty <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-beetle_regline_predInterval" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="P5_ANOVA_regression_files/figure-html/fig-beetle_regline_predInterval-1.png" class="img-fluid figure-img" width="384"></p>
<figcaption class="figure-caption">Figure&nbsp;5.7: Regression line (solid) with upper and lower 95% confidence intervals on the regression line (dashed) and 95% prediction intervals (dotted).</figcaption></figure>
</div>
</div>
</div>
<p>These are prediction intervals and they are broader than confidence intervals. The confidence intervals express your confidence about the <em>regression line</em> for the population. The prediction interval expresses your confidence about the distribution of the <em>observations</em> for the population. For more kicks, import the ‘PhosphateCalibration’ sheet (1st year practical data) into R and duplicate the following plots and confidence intervals.</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">phosphate_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readxl.tidyverse.org/reference/read_excel.html">read_xlsx</a></span><span class="op">(</span><span class="st">"data/Practical_6.xlsx"</span>, <span class="st">"PhosphateCalibration"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-phosphateScatter" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="P5_ANOVA_regression_files/figure-html/fig-phosphateScatter-1.png" class="img-fluid figure-img" width="384"></p>
<figcaption class="figure-caption">Figure&nbsp;5.8: Phosphate calibration scatter plot.</figcaption></figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-phosphateDiagnostics" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="P5_ANOVA_regression_files/figure-html/fig-phosphateDiagnostics-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption class="figure-caption">Figure&nbsp;5.9: Phosphate calibration regression diagnostics.</figcaption></figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Absorbance ~ Concentration, data = phosphate_df)

Residuals:
        1         2         3         4         5         6 
-0.001605 -0.001213 -0.003125  0.005355  0.005314 -0.004726 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   0.002605   0.002853   0.913 0.412856    
Concentration 0.023040   0.001849  12.464 0.000238 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.004823 on 4 degrees of freedom
Multiple R-squared:  0.9749,    Adjusted R-squared:  0.9686 
F-statistic: 155.3 on 1 and 4 DF,  p-value: 0.0002383</code></pre>
</div>
</div>
<p><em>Q182. Are you happy with your model assumptions?</em></p>
<p><em>Q183. Write down the regression equation.</em></p>
<p><em>Q184. Determine the 95% confidence interval for the regression line.</em></p>
<p><em>Q185. For a concentration of 0.75 units, what values would you expect (95 times in 100) to see from your experimental set-up?</em></p>
<p>You should get:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>         fit         lwr        upr
1 0.01988519 0.005298129 0.03447225</code></pre>
</div>
</div>
<hr></section></section><section id="conclusions" class="level2" data-number="5.3"><h2 data-number="5.3" class="anchored" data-anchor-id="conclusions">
<span class="header-section-number">5.3</span> Conclusions</h2>
<p>Correlation is a measure of association between two variables. It is appropriate to use correlation to measure this association when one cannot or does not wish to assume that any relationship is causative. Pearson correlation coefficients should only be used where it is fair to assume (by looking at scatter plot) that the relationship is approximately linear. Where linearity does not apply, attempt to transform one or both of the variables. Where there are outliers (that cannot be removed) or where one is uncertain about some of the data, then non-parametric ranked based correlation coefficients, such as the Spearman coefficient, should be used. As with GLMs, correlation analysis assumes that all points are independent of each other.</p>
<p>Linear regression is one of the most widely used statistical techniques. It is used to examine causal relationships, often where experimental manipulations are conducted. Regression is a general linear model and it lies within the generalized linear model family (GLMs). GLMs allow you to model data that is not normally distributed, including proportions (bounded by 0 and 1), or counts (bounded by 0). Using a GLM is a much better way of analyzing these data compared with transforming the response variable or using non-parametric techniques. All members of the GLM family make the assumptions that measurements are independent of each other. Where this assumption fails you can use generalized linear mixed models (GLMMs). Extensions of simple linear regression include multiple regression which examines the influence of two or more continuous variables on a response variable.</p>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./P4_t_CIs.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">T distribution and confidence intervals</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./P6_machine_learning.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Machine Learning</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>